error: Could not connect to the database. Access denied for user 'Mayur'@'localhost' (using password: YES) {"name":"SequelizeAccessDeniedError","original":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'Mayur'@'localhost' (using password: YES)","sqlState":"28000"},"parent":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'Mayur'@'localhost' (using password: YES)","sqlState":"28000"},"stack":"SequelizeAccessDeniedError: Access denied for user 'Mayur'@'localhost' (using password: YES)\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mysql\\connection-manager.js:118:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","timestamp":"2024-05-08T07:17:22.762Z"}
error: uncaughtException: Access denied for user 'Mayur'@'localhost' (using password: YES)
SequelizeAccessDeniedError: Access denied for user 'Mayur'@'localhost' (using password: YES)
    at ConnectionManager.connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\mysql\connection-manager.js:118:17)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ConnectionManager._connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:332:24)
    at D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:250:32 {"date":"Wed May 08 2024 12:47:22 GMT+0530 (India Standard Time)","error":{"name":"SequelizeAccessDeniedError","original":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'Mayur'@'localhost' (using password: YES)","sqlState":"28000"},"parent":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'Mayur'@'localhost' (using password: YES)","sqlState":"28000"}},"exception":true,"os":{"loadavg":[0,0,0],"uptime":1205669.14},"process":{"argv":["node","D:\\CPAI_Node\\demo_project\\src\\index.js"],"cwd":"D:\\CPAI_Node\\demo_project","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":42641,"external":3085657,"heapTotal":98205696,"heapUsed":44609920,"rss":136155136},"pid":28816,"uid":null,"version":"v20.10.0"},"stack":"SequelizeAccessDeniedError: Access denied for user 'Mayur'@'localhost' (using password: YES)\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mysql\\connection-manager.js:118:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","timestamp":"2024-05-08T07:17:22.767Z","trace":[{"column":17,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mysql\\connection-manager.js","function":"ConnectionManager.connect","line":118,"method":"connect","native":false},{"column":5,"file":"node:internal/process/task_queues","function":"processTicksAndRejections","line":95,"method":null,"native":false},{"column":24,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":"ConnectionManager._connect","line":332,"method":"_connect","native":false},{"column":32,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":null,"line":250,"method":null,"native":false}]}
error: Could not connect to the database. Access denied for user 'Mayur'@'localhost' (using password: YES) {"name":"SequelizeAccessDeniedError","original":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'Mayur'@'localhost' (using password: YES)","sqlState":"28000"},"parent":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'Mayur'@'localhost' (using password: YES)","sqlState":"28000"},"stack":"SequelizeAccessDeniedError: Access denied for user 'Mayur'@'localhost' (using password: YES)\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mysql\\connection-manager.js:118:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","timestamp":"2024-05-08T07:18:16.053Z"}
error: uncaughtException: Access denied for user 'Mayur'@'localhost' (using password: YES)
SequelizeAccessDeniedError: Access denied for user 'Mayur'@'localhost' (using password: YES)
    at ConnectionManager.connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\mysql\connection-manager.js:118:17)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ConnectionManager._connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:332:24)
    at D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:250:32 {"date":"Wed May 08 2024 12:48:16 GMT+0530 (India Standard Time)","error":{"name":"SequelizeAccessDeniedError","original":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'Mayur'@'localhost' (using password: YES)","sqlState":"28000"},"parent":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'Mayur'@'localhost' (using password: YES)","sqlState":"28000"}},"exception":true,"os":{"loadavg":[0,0,0],"uptime":1205722.421},"process":{"argv":["node","D:\\CPAI_Node\\demo_project\\src\\index.js"],"cwd":"D:\\CPAI_Node\\demo_project","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":18065,"external":3061081,"heapTotal":92561408,"heapUsed":42743040,"rss":128225280},"pid":43900,"uid":null,"version":"v20.10.0"},"stack":"SequelizeAccessDeniedError: Access denied for user 'Mayur'@'localhost' (using password: YES)\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mysql\\connection-manager.js:118:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","timestamp":"2024-05-08T07:18:16.058Z","trace":[{"column":17,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mysql\\connection-manager.js","function":"ConnectionManager.connect","line":118,"method":"connect","native":false},{"column":5,"file":"node:internal/process/task_queues","function":"processTicksAndRejections","line":95,"method":null,"native":false},{"column":24,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":"ConnectionManager._connect","line":332,"method":"_connect","native":false},{"column":32,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":null,"line":250,"method":null,"native":false}]}
error: Could not connect to the database. Access denied for user 'Mayur'@'localhost' (using password: YES) {"name":"SequelizeAccessDeniedError","original":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'Mayur'@'localhost' (using password: YES)","sqlState":"28000"},"parent":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'Mayur'@'localhost' (using password: YES)","sqlState":"28000"},"stack":"SequelizeAccessDeniedError: Access denied for user 'Mayur'@'localhost' (using password: YES)\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mysql\\connection-manager.js:118:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","timestamp":"2024-05-08T07:20:53.876Z"}
error: uncaughtException: Access denied for user 'Mayur'@'localhost' (using password: YES)
SequelizeAccessDeniedError: Access denied for user 'Mayur'@'localhost' (using password: YES)
    at ConnectionManager.connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\mysql\connection-manager.js:118:17)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ConnectionManager._connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:332:24)
    at D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:250:32 {"date":"Wed May 08 2024 12:50:53 GMT+0530 (India Standard Time)","error":{"name":"SequelizeAccessDeniedError","original":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'Mayur'@'localhost' (using password: YES)","sqlState":"28000"},"parent":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'Mayur'@'localhost' (using password: YES)","sqlState":"28000"}},"exception":true,"os":{"loadavg":[0,0,0],"uptime":1205880.25},"process":{"argv":["node","D:\\CPAI_Node\\demo_project\\src\\index.js"],"cwd":"D:\\CPAI_Node\\demo_project","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":354975,"external":3401422,"heapTotal":88702976,"heapUsed":62465568,"rss":126828544},"pid":16616,"uid":null,"version":"v20.10.0"},"stack":"SequelizeAccessDeniedError: Access denied for user 'Mayur'@'localhost' (using password: YES)\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mysql\\connection-manager.js:118:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","timestamp":"2024-05-08T07:20:53.880Z","trace":[{"column":17,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mysql\\connection-manager.js","function":"ConnectionManager.connect","line":118,"method":"connect","native":false},{"column":5,"file":"node:internal/process/task_queues","function":"processTicksAndRejections","line":95,"method":null,"native":false},{"column":24,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":"ConnectionManager._connect","line":332,"method":"_connect","native":false},{"column":32,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":null,"line":250,"method":null,"native":false}]}
error: Could not connect to the database. Access denied for user 'Mayur'@'localhost' (using password: YES) {"name":"SequelizeAccessDeniedError","original":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'Mayur'@'localhost' (using password: YES)","sqlState":"28000"},"parent":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'Mayur'@'localhost' (using password: YES)","sqlState":"28000"},"stack":"SequelizeAccessDeniedError: Access denied for user 'Mayur'@'localhost' (using password: YES)\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mysql\\connection-manager.js:118:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","timestamp":"2024-05-08T07:20:57.775Z"}
error: uncaughtException: Access denied for user 'Mayur'@'localhost' (using password: YES)
SequelizeAccessDeniedError: Access denied for user 'Mayur'@'localhost' (using password: YES)
    at ConnectionManager.connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\mysql\connection-manager.js:118:17)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ConnectionManager._connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:332:24)
    at D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:250:32 {"date":"Wed May 08 2024 12:50:57 GMT+0530 (India Standard Time)","error":{"name":"SequelizeAccessDeniedError","original":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'Mayur'@'localhost' (using password: YES)","sqlState":"28000"},"parent":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'Mayur'@'localhost' (using password: YES)","sqlState":"28000"}},"exception":true,"os":{"loadavg":[0,0,0],"uptime":1205884.14},"process":{"argv":["node","D:\\CPAI_Node\\demo_project\\src\\index.js"],"cwd":"D:\\CPAI_Node\\demo_project","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":18065,"external":3061081,"heapTotal":91774976,"heapUsed":42497696,"rss":128151552},"pid":31920,"uid":null,"version":"v20.10.0"},"stack":"SequelizeAccessDeniedError: Access denied for user 'Mayur'@'localhost' (using password: YES)\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mysql\\connection-manager.js:118:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","timestamp":"2024-05-08T07:20:57.778Z","trace":[{"column":17,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mysql\\connection-manager.js","function":"ConnectionManager.connect","line":118,"method":"connect","native":false},{"column":5,"file":"node:internal/process/task_queues","function":"processTicksAndRejections","line":95,"method":null,"native":false},{"column":24,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":"ConnectionManager._connect","line":332,"method":"_connect","native":false},{"column":32,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":null,"line":250,"method":null,"native":false}]}
error: Could not connect to the database. Access denied for user 'Mayur'@'localhost' (using password: YES) {"name":"SequelizeAccessDeniedError","original":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'Mayur'@'localhost' (using password: YES)","sqlState":"28000"},"parent":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'Mayur'@'localhost' (using password: YES)","sqlState":"28000"},"stack":"SequelizeAccessDeniedError: Access denied for user 'Mayur'@'localhost' (using password: YES)\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mysql\\connection-manager.js:118:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","timestamp":"2024-05-08T07:41:22.947Z"}
error: uncaughtException: Access denied for user 'Mayur'@'localhost' (using password: YES)
SequelizeAccessDeniedError: Access denied for user 'Mayur'@'localhost' (using password: YES)
    at ConnectionManager.connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\mysql\connection-manager.js:118:17)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ConnectionManager._connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:332:24)
    at D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:250:32 {"date":"Wed May 08 2024 13:11:22 GMT+0530 (India Standard Time)","error":{"name":"SequelizeAccessDeniedError","original":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'Mayur'@'localhost' (using password: YES)","sqlState":"28000"},"parent":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'Mayur'@'localhost' (using password: YES)","sqlState":"28000"}},"exception":true,"os":{"loadavg":[0,0,0],"uptime":1207109.312},"process":{"argv":["node","D:\\CPAI_Node\\demo_project\\src\\index.js"],"cwd":"D:\\CPAI_Node\\demo_project","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":26257,"external":3069273,"heapTotal":90988544,"heapUsed":42307552,"rss":126341120},"pid":40476,"uid":null,"version":"v20.10.0"},"stack":"SequelizeAccessDeniedError: Access denied for user 'Mayur'@'localhost' (using password: YES)\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mysql\\connection-manager.js:118:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","timestamp":"2024-05-08T07:41:22.950Z","trace":[{"column":17,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mysql\\connection-manager.js","function":"ConnectionManager.connect","line":118,"method":"connect","native":false},{"column":5,"file":"node:internal/process/task_queues","function":"processTicksAndRejections","line":95,"method":null,"native":false},{"column":24,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":"ConnectionManager._connect","line":332,"method":"_connect","native":false},{"column":32,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":null,"line":250,"method":null,"native":false}]}
error: Could not connect to the database. Access denied for user 'Mayur'@'localhost' (using password: YES) {"name":"SequelizeAccessDeniedError","original":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'Mayur'@'localhost' (using password: YES)","sqlState":"28000"},"parent":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'Mayur'@'localhost' (using password: YES)","sqlState":"28000"},"stack":"SequelizeAccessDeniedError: Access denied for user 'Mayur'@'localhost' (using password: YES)\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mysql\\connection-manager.js:118:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","timestamp":"2024-05-08T07:42:23.847Z"}
error: uncaughtException: Access denied for user 'Mayur'@'localhost' (using password: YES)
SequelizeAccessDeniedError: Access denied for user 'Mayur'@'localhost' (using password: YES)
    at ConnectionManager.connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\mysql\connection-manager.js:118:17)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ConnectionManager._connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:332:24)
    at D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:250:32 {"date":"Wed May 08 2024 13:12:23 GMT+0530 (India Standard Time)","error":{"name":"SequelizeAccessDeniedError","original":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'Mayur'@'localhost' (using password: YES)","sqlState":"28000"},"parent":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'Mayur'@'localhost' (using password: YES)","sqlState":"28000"}},"exception":true,"os":{"loadavg":[0,0,0],"uptime":1207170.218},"process":{"argv":["node","D:\\CPAI_Node\\demo_project\\src\\index.js"],"cwd":"D:\\CPAI_Node\\demo_project","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":18065,"external":3061081,"heapTotal":90202112,"heapUsed":41630128,"rss":126312448},"pid":15780,"uid":null,"version":"v20.10.0"},"stack":"SequelizeAccessDeniedError: Access denied for user 'Mayur'@'localhost' (using password: YES)\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mysql\\connection-manager.js:118:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","timestamp":"2024-05-08T07:42:23.850Z","trace":[{"column":17,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mysql\\connection-manager.js","function":"ConnectionManager.connect","line":118,"method":"connect","native":false},{"column":5,"file":"node:internal/process/task_queues","function":"processTicksAndRejections","line":95,"method":null,"native":false},{"column":24,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":"ConnectionManager._connect","line":332,"method":"_connect","native":false},{"column":32,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":null,"line":250,"method":null,"native":false}]}
error: Could not connect to the database. Access denied for user 'Mayur'@'localhost' (using password: YES) {"name":"SequelizeAccessDeniedError","original":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'Mayur'@'localhost' (using password: YES)","sqlState":"28000"},"parent":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'Mayur'@'localhost' (using password: YES)","sqlState":"28000"},"stack":"SequelizeAccessDeniedError: Access denied for user 'Mayur'@'localhost' (using password: YES)\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mysql\\connection-manager.js:118:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","timestamp":"2024-05-08T07:44:24.780Z"}
error: uncaughtException: Access denied for user 'Mayur'@'localhost' (using password: YES)
SequelizeAccessDeniedError: Access denied for user 'Mayur'@'localhost' (using password: YES)
    at ConnectionManager.connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\mysql\connection-manager.js:118:17)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ConnectionManager._connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:332:24)
    at D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:250:32 {"date":"Wed May 08 2024 13:14:24 GMT+0530 (India Standard Time)","error":{"name":"SequelizeAccessDeniedError","original":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'Mayur'@'localhost' (using password: YES)","sqlState":"28000"},"parent":{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlMessage":"Access denied for user 'Mayur'@'localhost' (using password: YES)","sqlState":"28000"}},"exception":true,"os":{"loadavg":[0,0,0],"uptime":1207291.156},"process":{"argv":["node","D:\\CPAI_Node\\demo_project\\src\\index.js"],"cwd":"D:\\CPAI_Node\\demo_project","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":18065,"external":3061081,"heapTotal":91512832,"heapUsed":42383216,"rss":128667648},"pid":41508,"uid":null,"version":"v20.10.0"},"stack":"SequelizeAccessDeniedError: Access denied for user 'Mayur'@'localhost' (using password: YES)\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mysql\\connection-manager.js:118:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","timestamp":"2024-05-08T07:44:24.783Z","trace":[{"column":17,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mysql\\connection-manager.js","function":"ConnectionManager.connect","line":118,"method":"connect","native":false},{"column":5,"file":"node:internal/process/task_queues","function":"processTicksAndRejections","line":95,"method":null,"native":false},{"column":24,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":"ConnectionManager._connect","line":332,"method":"_connect","native":false},{"column":32,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":null,"line":250,"method":null,"native":false}]}
error: uncaughtException: Please install tedious package manually
Error: Please install tedious package manually
    at ConnectionManager._loadDialectModule (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:81:15)
    at new ConnectionManager (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\mssql\connection-manager.js:16:21)
    at new MssqlDialect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\mssql\index.js:15:30)
    at new Sequelize (D:\CPAI_Node\demo_project\node_modules\sequelize\src\sequelize.js:368:20)
    at Object.<anonymous> (D:\CPAI_Node\demo_project\src\config\/database.js:25:19)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._compile (D:\CPAI_Node\demo_project\node_modules\pirates\lib\index.js:117:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Object.newLoader [as .js] (D:\CPAI_Node\demo_project\node_modules\pirates\lib\index.js:121:7)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (D:\CPAI_Node\demo_project\src\services\/user.service.js:1:1)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._compile (D:\CPAI_Node\demo_project\node_modules\pirates\lib\index.js:117:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Object.newLoader [as .js] (D:\CPAI_Node\demo_project\node_modules\pirates\lib\index.js:121:7)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (D:\CPAI_Node\demo_project\src\controllers\/user.controller.js:2:1)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._compile (D:\CPAI_Node\demo_project\node_modules\pirates\lib\index.js:117:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Object.newLoader [as .js] (D:\CPAI_Node\demo_project\node_modules\pirates\lib\index.js:121:7)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (D:\CPAI_Node\demo_project\src\routes\/user.route.js:2:1)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._compile (D:\CPAI_Node\demo_project\node_modules\pirates\lib\index.js:117:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Object.newLoader [as .js] (D:\CPAI_Node\demo_project\node_modules\pirates\lib\index.js:121:7)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (D:\CPAI_Node\demo_project\src\routes\/index.js:4:1)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._compile (D:\CPAI_Node\demo_project\node_modules\pirates\lib\index.js:117:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Object.newLoader [as .js] (D:\CPAI_Node\demo_project\node_modules\pirates\lib\index.js:121:7)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (D:\CPAI_Node\demo_project\src\/index.js:8:1) {"date":"Wed May 08 2024 14:39:38 GMT+0530 (India Standard Time)","error":{},"exception":true,"os":{"loadavg":[0,0,0],"uptime":1212405.203},"process":{"argv":["node","D:\\CPAI_Node\\demo_project\\src\\index.js"],"cwd":"D:\\CPAI_Node\\demo_project","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":16999,"external":2951018,"heapTotal":82337792,"heapUsed":57864552,"rss":118652928},"pid":34496,"uid":null,"version":"v20.10.0"},"stack":"Error: Please install tedious package manually\n    at ConnectionManager._loadDialectModule (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:81:15)\n    at new ConnectionManager (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js:16:21)\n    at new MssqlDialect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\index.js:15:30)\n    at new Sequelize (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\sequelize.js:368:20)\n    at Object.<anonymous> (D:\\CPAI_Node\\demo_project\\src\\config\\/database.js:25:19)\n    at Module._compile (node:internal/modules/cjs/loader:1376:14)\n    at Module._compile (D:\\CPAI_Node\\demo_project\\node_modules\\pirates\\lib\\index.js:117:24)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)\n    at Object.newLoader [as .js] (D:\\CPAI_Node\\demo_project\\node_modules\\pirates\\lib\\index.js:121:7)\n    at Module.load (node:internal/modules/cjs/loader:1207:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:1023:12)\n    at Module.require (node:internal/modules/cjs/loader:1235:19)\n    at require (node:internal/modules/helpers:176:18)\n    at Object.<anonymous> (D:\\CPAI_Node\\demo_project\\src\\services\\/user.service.js:1:1)\n    at Module._compile (node:internal/modules/cjs/loader:1376:14)\n    at Module._compile (D:\\CPAI_Node\\demo_project\\node_modules\\pirates\\lib\\index.js:117:24)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)\n    at Object.newLoader [as .js] (D:\\CPAI_Node\\demo_project\\node_modules\\pirates\\lib\\index.js:121:7)\n    at Module.load (node:internal/modules/cjs/loader:1207:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:1023:12)\n    at Module.require (node:internal/modules/cjs/loader:1235:19)\n    at require (node:internal/modules/helpers:176:18)\n    at Object.<anonymous> (D:\\CPAI_Node\\demo_project\\src\\controllers\\/user.controller.js:2:1)\n    at Module._compile (node:internal/modules/cjs/loader:1376:14)\n    at Module._compile (D:\\CPAI_Node\\demo_project\\node_modules\\pirates\\lib\\index.js:117:24)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)\n    at Object.newLoader [as .js] (D:\\CPAI_Node\\demo_project\\node_modules\\pirates\\lib\\index.js:121:7)\n    at Module.load (node:internal/modules/cjs/loader:1207:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:1023:12)\n    at Module.require (node:internal/modules/cjs/loader:1235:19)\n    at require (node:internal/modules/helpers:176:18)\n    at Object.<anonymous> (D:\\CPAI_Node\\demo_project\\src\\routes\\/user.route.js:2:1)\n    at Module._compile (node:internal/modules/cjs/loader:1376:14)\n    at Module._compile (D:\\CPAI_Node\\demo_project\\node_modules\\pirates\\lib\\index.js:117:24)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)\n    at Object.newLoader [as .js] (D:\\CPAI_Node\\demo_project\\node_modules\\pirates\\lib\\index.js:121:7)\n    at Module.load (node:internal/modules/cjs/loader:1207:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:1023:12)\n    at Module.require (node:internal/modules/cjs/loader:1235:19)\n    at require (node:internal/modules/helpers:176:18)\n    at Object.<anonymous> (D:\\CPAI_Node\\demo_project\\src\\routes\\/index.js:4:1)\n    at Module._compile (node:internal/modules/cjs/loader:1376:14)\n    at Module._compile (D:\\CPAI_Node\\demo_project\\node_modules\\pirates\\lib\\index.js:117:24)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)\n    at Object.newLoader [as .js] (D:\\CPAI_Node\\demo_project\\node_modules\\pirates\\lib\\index.js:121:7)\n    at Module.load (node:internal/modules/cjs/loader:1207:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:1023:12)\n    at Module.require (node:internal/modules/cjs/loader:1235:19)\n    at require (node:internal/modules/helpers:176:18)\n    at Object.<anonymous> (D:\\CPAI_Node\\demo_project\\src\\/index.js:8:1)","timestamp":"2024-05-08T09:09:38.843Z","trace":[{"column":15,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":"ConnectionManager._loadDialectModule","line":81,"method":"_loadDialectModule","native":false},{"column":21,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js","function":"new ConnectionManager","line":16,"method":null,"native":false},{"column":30,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\index.js","function":"new MssqlDialect","line":15,"method":null,"native":false},{"column":20,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\sequelize.js","function":"new Sequelize","line":368,"method":null,"native":false},{"column":19,"file":"D:\\CPAI_Node\\demo_project\\src\\config\\/database.js","function":null,"line":25,"method":null,"native":false},{"column":14,"file":"node:internal/modules/cjs/loader","function":"Module._compile","line":1376,"method":"_compile","native":false},{"column":24,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\pirates\\lib\\index.js","function":"Module._compile","line":117,"method":"_compile","native":false},{"column":10,"file":"node:internal/modules/cjs/loader","function":"Module._extensions..js","line":1435,"method":".js","native":false},{"column":7,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\pirates\\lib\\index.js","function":"Object.newLoader [as .js]","line":121,"method":"js]","native":false},{"column":32,"file":"node:internal/modules/cjs/loader","function":"Module.load","line":1207,"method":"load","native":false},{"column":12,"file":"node:internal/modules/cjs/loader","function":"Module._load","line":1023,"method":"_load","native":false},{"column":19,"file":"node:internal/modules/cjs/loader","function":"Module.require","line":1235,"method":"require","native":false},{"column":18,"file":"node:internal/modules/helpers","function":"require","line":176,"method":null,"native":false},{"column":1,"file":"D:\\CPAI_Node\\demo_project\\src\\services\\/user.service.js","function":null,"line":1,"method":null,"native":false},{"column":14,"file":"node:internal/modules/cjs/loader","function":"Module._compile","line":1376,"method":"_compile","native":false},{"column":24,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\pirates\\lib\\index.js","function":"Module._compile","line":117,"method":"_compile","native":false},{"column":10,"file":"node:internal/modules/cjs/loader","function":"Module._extensions..js","line":1435,"method":".js","native":false},{"column":7,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\pirates\\lib\\index.js","function":"Object.newLoader [as .js]","line":121,"method":"js]","native":false},{"column":32,"file":"node:internal/modules/cjs/loader","function":"Module.load","line":1207,"method":"load","native":false},{"column":12,"file":"node:internal/modules/cjs/loader","function":"Module._load","line":1023,"method":"_load","native":false},{"column":19,"file":"node:internal/modules/cjs/loader","function":"Module.require","line":1235,"method":"require","native":false},{"column":18,"file":"node:internal/modules/helpers","function":"require","line":176,"method":null,"native":false},{"column":1,"file":"D:\\CPAI_Node\\demo_project\\src\\controllers\\/user.controller.js","function":null,"line":2,"method":null,"native":false},{"column":14,"file":"node:internal/modules/cjs/loader","function":"Module._compile","line":1376,"method":"_compile","native":false},{"column":24,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\pirates\\lib\\index.js","function":"Module._compile","line":117,"method":"_compile","native":false},{"column":10,"file":"node:internal/modules/cjs/loader","function":"Module._extensions..js","line":1435,"method":".js","native":false},{"column":7,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\pirates\\lib\\index.js","function":"Object.newLoader [as .js]","line":121,"method":"js]","native":false},{"column":32,"file":"node:internal/modules/cjs/loader","function":"Module.load","line":1207,"method":"load","native":false},{"column":12,"file":"node:internal/modules/cjs/loader","function":"Module._load","line":1023,"method":"_load","native":false},{"column":19,"file":"node:internal/modules/cjs/loader","function":"Module.require","line":1235,"method":"require","native":false},{"column":18,"file":"node:internal/modules/helpers","function":"require","line":176,"method":null,"native":false},{"column":1,"file":"D:\\CPAI_Node\\demo_project\\src\\routes\\/user.route.js","function":null,"line":2,"method":null,"native":false},{"column":14,"file":"node:internal/modules/cjs/loader","function":"Module._compile","line":1376,"method":"_compile","native":false},{"column":24,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\pirates\\lib\\index.js","function":"Module._compile","line":117,"method":"_compile","native":false},{"column":10,"file":"node:internal/modules/cjs/loader","function":"Module._extensions..js","line":1435,"method":".js","native":false},{"column":7,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\pirates\\lib\\index.js","function":"Object.newLoader [as .js]","line":121,"method":"js]","native":false},{"column":32,"file":"node:internal/modules/cjs/loader","function":"Module.load","line":1207,"method":"load","native":false},{"column":12,"file":"node:internal/modules/cjs/loader","function":"Module._load","line":1023,"method":"_load","native":false},{"column":19,"file":"node:internal/modules/cjs/loader","function":"Module.require","line":1235,"method":"require","native":false},{"column":18,"file":"node:internal/modules/helpers","function":"require","line":176,"method":null,"native":false},{"column":1,"file":"D:\\CPAI_Node\\demo_project\\src\\routes\\/index.js","function":null,"line":4,"method":null,"native":false},{"column":14,"file":"node:internal/modules/cjs/loader","function":"Module._compile","line":1376,"method":"_compile","native":false},{"column":24,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\pirates\\lib\\index.js","function":"Module._compile","line":117,"method":"_compile","native":false},{"column":10,"file":"node:internal/modules/cjs/loader","function":"Module._extensions..js","line":1435,"method":".js","native":false},{"column":7,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\pirates\\lib\\index.js","function":"Object.newLoader [as .js]","line":121,"method":"js]","native":false},{"column":32,"file":"node:internal/modules/cjs/loader","function":"Module.load","line":1207,"method":"load","native":false},{"column":12,"file":"node:internal/modules/cjs/loader","function":"Module._load","line":1023,"method":"_load","native":false},{"column":19,"file":"node:internal/modules/cjs/loader","function":"Module.require","line":1235,"method":"require","native":false},{"column":18,"file":"node:internal/modules/helpers","function":"require","line":176,"method":null,"native":false},{"column":1,"file":"D:\\CPAI_Node\\demo_project\\src\\/index.js","function":null,"line":8,"method":null,"native":false}]}
error: uncaughtException: Please install tedious package manually
Error: Please install tedious package manually
    at ConnectionManager._loadDialectModule (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:81:15)
    at new ConnectionManager (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\mssql\connection-manager.js:16:21)
    at new MssqlDialect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\mssql\index.js:15:30)
    at new Sequelize (D:\CPAI_Node\demo_project\node_modules\sequelize\src\sequelize.js:368:20)
    at Object.<anonymous> (D:\CPAI_Node\demo_project\src\config\/database.js:25:19)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._compile (D:\CPAI_Node\demo_project\node_modules\pirates\lib\index.js:117:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Object.newLoader [as .js] (D:\CPAI_Node\demo_project\node_modules\pirates\lib\index.js:121:7)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (D:\CPAI_Node\demo_project\src\services\/user.service.js:1:1)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._compile (D:\CPAI_Node\demo_project\node_modules\pirates\lib\index.js:117:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Object.newLoader [as .js] (D:\CPAI_Node\demo_project\node_modules\pirates\lib\index.js:121:7)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (D:\CPAI_Node\demo_project\src\controllers\/user.controller.js:2:1)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._compile (D:\CPAI_Node\demo_project\node_modules\pirates\lib\index.js:117:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Object.newLoader [as .js] (D:\CPAI_Node\demo_project\node_modules\pirates\lib\index.js:121:7)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (D:\CPAI_Node\demo_project\src\routes\/user.route.js:2:1)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._compile (D:\CPAI_Node\demo_project\node_modules\pirates\lib\index.js:117:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Object.newLoader [as .js] (D:\CPAI_Node\demo_project\node_modules\pirates\lib\index.js:121:7)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (D:\CPAI_Node\demo_project\src\routes\/index.js:4:1)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._compile (D:\CPAI_Node\demo_project\node_modules\pirates\lib\index.js:117:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Object.newLoader [as .js] (D:\CPAI_Node\demo_project\node_modules\pirates\lib\index.js:121:7)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (D:\CPAI_Node\demo_project\src\/index.js:8:1) {"date":"Wed May 08 2024 14:43:16 GMT+0530 (India Standard Time)","error":{},"exception":true,"os":{"loadavg":[0,0,0],"uptime":1212623.078},"process":{"argv":["node","D:\\CPAI_Node\\demo_project\\src\\index.js"],"cwd":"D:\\CPAI_Node\\demo_project","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":16999,"external":2951018,"heapTotal":82075648,"heapUsed":58077056,"rss":118857728},"pid":39576,"uid":null,"version":"v20.10.0"},"stack":"Error: Please install tedious package manually\n    at ConnectionManager._loadDialectModule (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:81:15)\n    at new ConnectionManager (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js:16:21)\n    at new MssqlDialect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\index.js:15:30)\n    at new Sequelize (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\sequelize.js:368:20)\n    at Object.<anonymous> (D:\\CPAI_Node\\demo_project\\src\\config\\/database.js:25:19)\n    at Module._compile (node:internal/modules/cjs/loader:1376:14)\n    at Module._compile (D:\\CPAI_Node\\demo_project\\node_modules\\pirates\\lib\\index.js:117:24)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)\n    at Object.newLoader [as .js] (D:\\CPAI_Node\\demo_project\\node_modules\\pirates\\lib\\index.js:121:7)\n    at Module.load (node:internal/modules/cjs/loader:1207:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:1023:12)\n    at Module.require (node:internal/modules/cjs/loader:1235:19)\n    at require (node:internal/modules/helpers:176:18)\n    at Object.<anonymous> (D:\\CPAI_Node\\demo_project\\src\\services\\/user.service.js:1:1)\n    at Module._compile (node:internal/modules/cjs/loader:1376:14)\n    at Module._compile (D:\\CPAI_Node\\demo_project\\node_modules\\pirates\\lib\\index.js:117:24)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)\n    at Object.newLoader [as .js] (D:\\CPAI_Node\\demo_project\\node_modules\\pirates\\lib\\index.js:121:7)\n    at Module.load (node:internal/modules/cjs/loader:1207:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:1023:12)\n    at Module.require (node:internal/modules/cjs/loader:1235:19)\n    at require (node:internal/modules/helpers:176:18)\n    at Object.<anonymous> (D:\\CPAI_Node\\demo_project\\src\\controllers\\/user.controller.js:2:1)\n    at Module._compile (node:internal/modules/cjs/loader:1376:14)\n    at Module._compile (D:\\CPAI_Node\\demo_project\\node_modules\\pirates\\lib\\index.js:117:24)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)\n    at Object.newLoader [as .js] (D:\\CPAI_Node\\demo_project\\node_modules\\pirates\\lib\\index.js:121:7)\n    at Module.load (node:internal/modules/cjs/loader:1207:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:1023:12)\n    at Module.require (node:internal/modules/cjs/loader:1235:19)\n    at require (node:internal/modules/helpers:176:18)\n    at Object.<anonymous> (D:\\CPAI_Node\\demo_project\\src\\routes\\/user.route.js:2:1)\n    at Module._compile (node:internal/modules/cjs/loader:1376:14)\n    at Module._compile (D:\\CPAI_Node\\demo_project\\node_modules\\pirates\\lib\\index.js:117:24)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)\n    at Object.newLoader [as .js] (D:\\CPAI_Node\\demo_project\\node_modules\\pirates\\lib\\index.js:121:7)\n    at Module.load (node:internal/modules/cjs/loader:1207:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:1023:12)\n    at Module.require (node:internal/modules/cjs/loader:1235:19)\n    at require (node:internal/modules/helpers:176:18)\n    at Object.<anonymous> (D:\\CPAI_Node\\demo_project\\src\\routes\\/index.js:4:1)\n    at Module._compile (node:internal/modules/cjs/loader:1376:14)\n    at Module._compile (D:\\CPAI_Node\\demo_project\\node_modules\\pirates\\lib\\index.js:117:24)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)\n    at Object.newLoader [as .js] (D:\\CPAI_Node\\demo_project\\node_modules\\pirates\\lib\\index.js:121:7)\n    at Module.load (node:internal/modules/cjs/loader:1207:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:1023:12)\n    at Module.require (node:internal/modules/cjs/loader:1235:19)\n    at require (node:internal/modules/helpers:176:18)\n    at Object.<anonymous> (D:\\CPAI_Node\\demo_project\\src\\/index.js:8:1)","timestamp":"2024-05-08T09:13:16.712Z","trace":[{"column":15,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":"ConnectionManager._loadDialectModule","line":81,"method":"_loadDialectModule","native":false},{"column":21,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js","function":"new ConnectionManager","line":16,"method":null,"native":false},{"column":30,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\index.js","function":"new MssqlDialect","line":15,"method":null,"native":false},{"column":20,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\sequelize.js","function":"new Sequelize","line":368,"method":null,"native":false},{"column":19,"file":"D:\\CPAI_Node\\demo_project\\src\\config\\/database.js","function":null,"line":25,"method":null,"native":false},{"column":14,"file":"node:internal/modules/cjs/loader","function":"Module._compile","line":1376,"method":"_compile","native":false},{"column":24,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\pirates\\lib\\index.js","function":"Module._compile","line":117,"method":"_compile","native":false},{"column":10,"file":"node:internal/modules/cjs/loader","function":"Module._extensions..js","line":1435,"method":".js","native":false},{"column":7,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\pirates\\lib\\index.js","function":"Object.newLoader [as .js]","line":121,"method":"js]","native":false},{"column":32,"file":"node:internal/modules/cjs/loader","function":"Module.load","line":1207,"method":"load","native":false},{"column":12,"file":"node:internal/modules/cjs/loader","function":"Module._load","line":1023,"method":"_load","native":false},{"column":19,"file":"node:internal/modules/cjs/loader","function":"Module.require","line":1235,"method":"require","native":false},{"column":18,"file":"node:internal/modules/helpers","function":"require","line":176,"method":null,"native":false},{"column":1,"file":"D:\\CPAI_Node\\demo_project\\src\\services\\/user.service.js","function":null,"line":1,"method":null,"native":false},{"column":14,"file":"node:internal/modules/cjs/loader","function":"Module._compile","line":1376,"method":"_compile","native":false},{"column":24,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\pirates\\lib\\index.js","function":"Module._compile","line":117,"method":"_compile","native":false},{"column":10,"file":"node:internal/modules/cjs/loader","function":"Module._extensions..js","line":1435,"method":".js","native":false},{"column":7,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\pirates\\lib\\index.js","function":"Object.newLoader [as .js]","line":121,"method":"js]","native":false},{"column":32,"file":"node:internal/modules/cjs/loader","function":"Module.load","line":1207,"method":"load","native":false},{"column":12,"file":"node:internal/modules/cjs/loader","function":"Module._load","line":1023,"method":"_load","native":false},{"column":19,"file":"node:internal/modules/cjs/loader","function":"Module.require","line":1235,"method":"require","native":false},{"column":18,"file":"node:internal/modules/helpers","function":"require","line":176,"method":null,"native":false},{"column":1,"file":"D:\\CPAI_Node\\demo_project\\src\\controllers\\/user.controller.js","function":null,"line":2,"method":null,"native":false},{"column":14,"file":"node:internal/modules/cjs/loader","function":"Module._compile","line":1376,"method":"_compile","native":false},{"column":24,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\pirates\\lib\\index.js","function":"Module._compile","line":117,"method":"_compile","native":false},{"column":10,"file":"node:internal/modules/cjs/loader","function":"Module._extensions..js","line":1435,"method":".js","native":false},{"column":7,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\pirates\\lib\\index.js","function":"Object.newLoader [as .js]","line":121,"method":"js]","native":false},{"column":32,"file":"node:internal/modules/cjs/loader","function":"Module.load","line":1207,"method":"load","native":false},{"column":12,"file":"node:internal/modules/cjs/loader","function":"Module._load","line":1023,"method":"_load","native":false},{"column":19,"file":"node:internal/modules/cjs/loader","function":"Module.require","line":1235,"method":"require","native":false},{"column":18,"file":"node:internal/modules/helpers","function":"require","line":176,"method":null,"native":false},{"column":1,"file":"D:\\CPAI_Node\\demo_project\\src\\routes\\/user.route.js","function":null,"line":2,"method":null,"native":false},{"column":14,"file":"node:internal/modules/cjs/loader","function":"Module._compile","line":1376,"method":"_compile","native":false},{"column":24,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\pirates\\lib\\index.js","function":"Module._compile","line":117,"method":"_compile","native":false},{"column":10,"file":"node:internal/modules/cjs/loader","function":"Module._extensions..js","line":1435,"method":".js","native":false},{"column":7,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\pirates\\lib\\index.js","function":"Object.newLoader [as .js]","line":121,"method":"js]","native":false},{"column":32,"file":"node:internal/modules/cjs/loader","function":"Module.load","line":1207,"method":"load","native":false},{"column":12,"file":"node:internal/modules/cjs/loader","function":"Module._load","line":1023,"method":"_load","native":false},{"column":19,"file":"node:internal/modules/cjs/loader","function":"Module.require","line":1235,"method":"require","native":false},{"column":18,"file":"node:internal/modules/helpers","function":"require","line":176,"method":null,"native":false},{"column":1,"file":"D:\\CPAI_Node\\demo_project\\src\\routes\\/index.js","function":null,"line":4,"method":null,"native":false},{"column":14,"file":"node:internal/modules/cjs/loader","function":"Module._compile","line":1376,"method":"_compile","native":false},{"column":24,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\pirates\\lib\\index.js","function":"Module._compile","line":117,"method":"_compile","native":false},{"column":10,"file":"node:internal/modules/cjs/loader","function":"Module._extensions..js","line":1435,"method":".js","native":false},{"column":7,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\pirates\\lib\\index.js","function":"Object.newLoader [as .js]","line":121,"method":"js]","native":false},{"column":32,"file":"node:internal/modules/cjs/loader","function":"Module.load","line":1207,"method":"load","native":false},{"column":12,"file":"node:internal/modules/cjs/loader","function":"Module._load","line":1023,"method":"_load","native":false},{"column":19,"file":"node:internal/modules/cjs/loader","function":"Module.require","line":1235,"method":"require","native":false},{"column":18,"file":"node:internal/modules/helpers","function":"require","line":176,"method":null,"native":false},{"column":1,"file":"D:\\CPAI_Node\\demo_project\\src\\/index.js","function":null,"line":8,"method":null,"native":false}]}
error: Could not connect to the database. Failed to connect to 127.0.0.1:1433 - Could not connect (sequence) {"name":"SequelizeConnectionError","original":{"code":"ESOCKET"},"parent":{"code":"ESOCKET"},"stack":"SequelizeConnectionError: Failed to connect to 127.0.0.1:1433 - Could not connect (sequence)\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js:141:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","timestamp":"2024-05-08T09:14:44.514Z"}
error: uncaughtException: Failed to connect to 127.0.0.1:1433 - Could not connect (sequence)
SequelizeConnectionError: Failed to connect to 127.0.0.1:1433 - Could not connect (sequence)
    at ConnectionManager.connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\mssql\connection-manager.js:141:17)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ConnectionManager._connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:332:24)
    at D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:250:32 {"date":"Wed May 08 2024 14:44:44 GMT+0530 (India Standard Time)","error":{"name":"SequelizeConnectionError","original":{"code":"ESOCKET"},"parent":{"code":"ESOCKET"}},"exception":true,"os":{"loadavg":[0,0,0],"uptime":1212710.89},"process":{"argv":["node","D:\\CPAI_Node\\demo_project\\src\\index.js"],"cwd":"D:\\CPAI_Node\\demo_project","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":17067,"external":3552153,"heapTotal":99979264,"heapUsed":49101752,"rss":134864896},"pid":29500,"uid":null,"version":"v20.10.0"},"stack":"SequelizeConnectionError: Failed to connect to 127.0.0.1:1433 - Could not connect (sequence)\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js:141:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","timestamp":"2024-05-08T09:14:44.520Z","trace":[{"column":17,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js","function":"ConnectionManager.connect","line":141,"method":"connect","native":false},{"column":5,"file":"node:internal/process/task_queues","function":"processTicksAndRejections","line":95,"method":null,"native":false},{"column":24,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":"ConnectionManager._connect","line":332,"method":"_connect","native":false},{"column":32,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":null,"line":250,"method":null,"native":false}]}
error: Could not connect to the database. Failed to connect to Mayur\LOCALDB#BDCCF332:1433 - Could not connect (sequence) {"name":"SequelizeConnectionError","original":{"code":"ESOCKET"},"parent":{"code":"ESOCKET"},"stack":"SequelizeConnectionError: Failed to connect to Mayur\\LOCALDB#BDCCF332:1433 - Could not connect (sequence)\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js:141:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","timestamp":"2024-05-08T09:16:53.566Z"}
error: uncaughtException: Failed to connect to Mayur\LOCALDB#BDCCF332:1433 - Could not connect (sequence)
SequelizeConnectionError: Failed to connect to Mayur\LOCALDB#BDCCF332:1433 - Could not connect (sequence)
    at ConnectionManager.connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\mssql\connection-manager.js:141:17)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ConnectionManager._connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:332:24)
    at D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:250:32 {"date":"Wed May 08 2024 14:46:53 GMT+0530 (India Standard Time)","error":{"name":"SequelizeConnectionError","original":{"code":"ESOCKET"},"parent":{"code":"ESOCKET"}},"exception":true,"os":{"loadavg":[0,0,0],"uptime":1212839.937},"process":{"argv":["node","D:\\CPAI_Node\\demo_project\\src\\index.js"],"cwd":"D:\\CPAI_Node\\demo_project","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":17067,"external":3574128,"heapTotal":96727040,"heapUsed":47638048,"rss":135458816},"pid":27360,"uid":null,"version":"v20.10.0"},"stack":"SequelizeConnectionError: Failed to connect to Mayur\\LOCALDB#BDCCF332:1433 - Could not connect (sequence)\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js:141:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","timestamp":"2024-05-08T09:16:53.572Z","trace":[{"column":17,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js","function":"ConnectionManager.connect","line":141,"method":"connect","native":false},{"column":5,"file":"node:internal/process/task_queues","function":"processTicksAndRejections","line":95,"method":null,"native":false},{"column":24,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":"ConnectionManager._connect","line":332,"method":"_connect","native":false},{"column":32,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":null,"line":250,"method":null,"native":false}]}
error: Could not connect to the database. Failed to connect to localhost:1433 - Could not connect (sequence) {"name":"SequelizeConnectionError","original":{"code":"ESOCKET"},"parent":{"code":"ESOCKET"},"stack":"SequelizeConnectionError: Failed to connect to localhost:1433 - Could not connect (sequence)\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js:141:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","timestamp":"2024-05-08T09:20:05.783Z"}
error: uncaughtException: Failed to connect to localhost:1433 - Could not connect (sequence)
SequelizeConnectionError: Failed to connect to localhost:1433 - Could not connect (sequence)
    at ConnectionManager.connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\mssql\connection-manager.js:141:17)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ConnectionManager._connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:332:24)
    at D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:250:32 {"date":"Wed May 08 2024 14:50:05 GMT+0530 (India Standard Time)","error":{"name":"SequelizeConnectionError","original":{"code":"ESOCKET"},"parent":{"code":"ESOCKET"}},"exception":true,"os":{"loadavg":[0,0,0],"uptime":1213032.156},"process":{"argv":["node","D:\\CPAI_Node\\demo_project\\src\\index.js"],"cwd":"D:\\CPAI_Node\\demo_project","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":17067,"external":3592715,"heapTotal":98299904,"heapUsed":48223768,"rss":134205440},"pid":11044,"uid":null,"version":"v20.10.0"},"stack":"SequelizeConnectionError: Failed to connect to localhost:1433 - Could not connect (sequence)\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js:141:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","timestamp":"2024-05-08T09:20:05.790Z","trace":[{"column":17,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js","function":"ConnectionManager.connect","line":141,"method":"connect","native":false},{"column":5,"file":"node:internal/process/task_queues","function":"processTicksAndRejections","line":95,"method":null,"native":false},{"column":24,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":"ConnectionManager._connect","line":332,"method":"_connect","native":false},{"column":32,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":null,"line":250,"method":null,"native":false}]}
error: Could not connect to the database. Failed to connect to localhost:1433 - Could not connect (sequence) {"name":"SequelizeConnectionError","original":{"code":"ESOCKET"},"parent":{"code":"ESOCKET"},"stack":"SequelizeConnectionError: Failed to connect to localhost:1433 - Could not connect (sequence)\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js:141:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","timestamp":"2024-05-08T09:51:35.710Z"}
error: uncaughtException: Failed to connect to localhost:1433 - Could not connect (sequence)
SequelizeConnectionError: Failed to connect to localhost:1433 - Could not connect (sequence)
    at ConnectionManager.connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\mssql\connection-manager.js:141:17)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ConnectionManager._connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:332:24)
    at D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:250:32 {"date":"Wed May 08 2024 15:21:35 GMT+0530 (India Standard Time)","error":{"name":"SequelizeConnectionError","original":{"code":"ESOCKET"},"parent":{"code":"ESOCKET"}},"exception":true,"os":{"loadavg":[0,0,0],"uptime":1214922.078},"process":{"argv":["node","D:\\CPAI_Node\\demo_project\\src\\index.js"],"cwd":"D:\\CPAI_Node\\demo_project","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":17067,"external":3631441,"heapTotal":98037760,"heapUsed":48802808,"rss":134488064},"pid":40432,"uid":null,"version":"v20.10.0"},"stack":"SequelizeConnectionError: Failed to connect to localhost:1433 - Could not connect (sequence)\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js:141:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","timestamp":"2024-05-08T09:51:35.715Z","trace":[{"column":17,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js","function":"ConnectionManager.connect","line":141,"method":"connect","native":false},{"column":5,"file":"node:internal/process/task_queues","function":"processTicksAndRejections","line":95,"method":null,"native":false},{"column":24,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":"ConnectionManager._connect","line":332,"method":"_connect","native":false},{"column":32,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":null,"line":250,"method":null,"native":false}]}
error: Could not connect to the database. Failed to connect to 127.0.0.1:1433 - Could not connect (sequence) {"name":"SequelizeConnectionError","original":{"code":"ESOCKET"},"parent":{"code":"ESOCKET"},"stack":"SequelizeConnectionError: Failed to connect to 127.0.0.1:1433 - Could not connect (sequence)\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js:141:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","timestamp":"2024-05-08T09:56:13.629Z"}
error: uncaughtException: Failed to connect to 127.0.0.1:1433 - Could not connect (sequence)
SequelizeConnectionError: Failed to connect to 127.0.0.1:1433 - Could not connect (sequence)
    at ConnectionManager.connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\mssql\connection-manager.js:141:17)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ConnectionManager._connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:332:24)
    at D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:250:32 {"date":"Wed May 08 2024 15:26:13 GMT+0530 (India Standard Time)","error":{"name":"SequelizeConnectionError","original":{"code":"ESOCKET"},"parent":{"code":"ESOCKET"}},"exception":true,"os":{"loadavg":[0,0,0],"uptime":1215200},"process":{"argv":["node","D:\\CPAI_Node\\demo_project\\src\\index.js"],"cwd":"D:\\CPAI_Node\\demo_project","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":587349,"external":3669420,"heapTotal":95813632,"heapUsed":69328312,"rss":135106560},"pid":35184,"uid":null,"version":"v20.10.0"},"stack":"SequelizeConnectionError: Failed to connect to 127.0.0.1:1433 - Could not connect (sequence)\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js:141:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","timestamp":"2024-05-08T09:56:13.633Z","trace":[{"column":17,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js","function":"ConnectionManager.connect","line":141,"method":"connect","native":false},{"column":5,"file":"node:internal/process/task_queues","function":"processTicksAndRejections","line":95,"method":null,"native":false},{"column":24,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":"ConnectionManager._connect","line":332,"method":"_connect","native":false},{"column":32,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":null,"line":250,"method":null,"native":false}]}
error: Could not connect to the database. Failed to connect to 127.0.0.1:1433 - Could not connect (sequence) {"name":"SequelizeConnectionError","original":{"code":"ESOCKET"},"parent":{"code":"ESOCKET"},"stack":"SequelizeConnectionError: Failed to connect to 127.0.0.1:1433 - Could not connect (sequence)\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js:141:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","timestamp":"2024-05-08T09:57:56.478Z"}
error: uncaughtException: Failed to connect to 127.0.0.1:1433 - Could not connect (sequence)
SequelizeConnectionError: Failed to connect to 127.0.0.1:1433 - Could not connect (sequence)
    at ConnectionManager.connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\mssql\connection-manager.js:141:17)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ConnectionManager._connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:332:24)
    at D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:250:32 {"date":"Wed May 08 2024 15:27:56 GMT+0530 (India Standard Time)","error":{"name":"SequelizeConnectionError","original":{"code":"ESOCKET"},"parent":{"code":"ESOCKET"}},"exception":true,"os":{"loadavg":[0,0,0],"uptime":1215302.843},"process":{"argv":["node","D:\\CPAI_Node\\demo_project\\src\\index.js"],"cwd":"D:\\CPAI_Node\\demo_project","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":17067,"external":3093877,"heapTotal":94998528,"heapUsed":45718168,"rss":130277376},"pid":38692,"uid":null,"version":"v20.10.0"},"stack":"SequelizeConnectionError: Failed to connect to 127.0.0.1:1433 - Could not connect (sequence)\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js:141:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","timestamp":"2024-05-08T09:57:56.483Z","trace":[{"column":17,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js","function":"ConnectionManager.connect","line":141,"method":"connect","native":false},{"column":5,"file":"node:internal/process/task_queues","function":"processTicksAndRejections","line":95,"method":null,"native":false},{"column":24,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":"ConnectionManager._connect","line":332,"method":"_connect","native":false},{"column":32,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":null,"line":250,"method":null,"native":false}]}
error: Could not connect to the database. Failed to connect to 127.0.0.1:1433 - Could not connect (sequence) {"name":"SequelizeConnectionError","original":{"code":"ESOCKET"},"parent":{"code":"ESOCKET"},"stack":"SequelizeConnectionError: Failed to connect to 127.0.0.1:1433 - Could not connect (sequence)\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js:141:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","timestamp":"2024-05-08T10:19:46.708Z"}
error: uncaughtException: Failed to connect to 127.0.0.1:1433 - Could not connect (sequence)
SequelizeConnectionError: Failed to connect to 127.0.0.1:1433 - Could not connect (sequence)
    at ConnectionManager.connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\mssql\connection-manager.js:141:17)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ConnectionManager._connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:332:24)
    at D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:250:32 {"date":"Wed May 08 2024 15:49:46 GMT+0530 (India Standard Time)","error":{"name":"SequelizeConnectionError","original":{"code":"ESOCKET"},"parent":{"code":"ESOCKET"}},"exception":true,"os":{"loadavg":[0,0,0],"uptime":1216613.078},"process":{"argv":["node","D:\\CPAI_Node\\demo_project\\src\\index.js"],"cwd":"D:\\CPAI_Node\\demo_project","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":563683,"external":3645754,"heapTotal":96075776,"heapUsed":72269896,"rss":135696384},"pid":23644,"uid":null,"version":"v20.10.0"},"stack":"SequelizeConnectionError: Failed to connect to 127.0.0.1:1433 - Could not connect (sequence)\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js:141:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","timestamp":"2024-05-08T10:19:46.715Z","trace":[{"column":17,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js","function":"ConnectionManager.connect","line":141,"method":"connect","native":false},{"column":5,"file":"node:internal/process/task_queues","function":"processTicksAndRejections","line":95,"method":null,"native":false},{"column":24,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":"ConnectionManager._connect","line":332,"method":"_connect","native":false},{"column":32,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":null,"line":250,"method":null,"native":false}]}
error: Could not connect to the database. Failed to connect to 127.0.0.1:1433 - Could not connect (sequence) {"name":"SequelizeConnectionError","original":{"code":"ESOCKET"},"parent":{"code":"ESOCKET"},"stack":"SequelizeConnectionError: Failed to connect to 127.0.0.1:1433 - Could not connect (sequence)\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js:141:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","timestamp":"2024-05-08T10:21:50.687Z"}
error: uncaughtException: Failed to connect to 127.0.0.1:1433 - Could not connect (sequence)
SequelizeConnectionError: Failed to connect to 127.0.0.1:1433 - Could not connect (sequence)
    at ConnectionManager.connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\mssql\connection-manager.js:141:17)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ConnectionManager._connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:332:24)
    at D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:250:32 {"date":"Wed May 08 2024 15:51:50 GMT+0530 (India Standard Time)","error":{"name":"SequelizeConnectionError","original":{"code":"ESOCKET"},"parent":{"code":"ESOCKET"}},"exception":true,"os":{"loadavg":[0,0,0],"uptime":1216737.062},"process":{"argv":["node","D:\\CPAI_Node\\demo_project\\src\\index.js"],"cwd":"D:\\CPAI_Node\\demo_project","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":562729,"external":3644800,"heapTotal":96075776,"heapUsed":72083360,"rss":135499776},"pid":21604,"uid":null,"version":"v20.10.0"},"stack":"SequelizeConnectionError: Failed to connect to 127.0.0.1:1433 - Could not connect (sequence)\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js:141:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","timestamp":"2024-05-08T10:21:50.695Z","trace":[{"column":17,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js","function":"ConnectionManager.connect","line":141,"method":"connect","native":false},{"column":5,"file":"node:internal/process/task_queues","function":"processTicksAndRejections","line":95,"method":null,"native":false},{"column":24,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":"ConnectionManager._connect","line":332,"method":"_connect","native":false},{"column":32,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":null,"line":250,"method":null,"native":false}]}
error: Could not connect to the database. Failed to connect to 127.0.0.1:1433 - Could not connect (sequence) {"name":"SequelizeConnectionError","original":{"code":"ESOCKET"},"parent":{"code":"ESOCKET"},"stack":"SequelizeConnectionError: Failed to connect to 127.0.0.1:1433 - Could not connect (sequence)\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js:141:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","timestamp":"2024-05-08T10:22:01.683Z"}
error: uncaughtException: Failed to connect to 127.0.0.1:1433 - Could not connect (sequence)
SequelizeConnectionError: Failed to connect to 127.0.0.1:1433 - Could not connect (sequence)
    at ConnectionManager.connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\mssql\connection-manager.js:141:17)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ConnectionManager._connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:332:24)
    at D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:250:32 {"date":"Wed May 08 2024 15:52:01 GMT+0530 (India Standard Time)","error":{"name":"SequelizeConnectionError","original":{"code":"ESOCKET"},"parent":{"code":"ESOCKET"}},"exception":true,"os":{"loadavg":[0,0,0],"uptime":1216748.062},"process":{"argv":["node","D:\\CPAI_Node\\demo_project\\src\\index.js"],"cwd":"D:\\CPAI_Node\\demo_project","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":17067,"external":3639583,"heapTotal":99192832,"heapUsed":48801704,"rss":134377472},"pid":29776,"uid":null,"version":"v20.10.0"},"stack":"SequelizeConnectionError: Failed to connect to 127.0.0.1:1433 - Could not connect (sequence)\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js:141:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","timestamp":"2024-05-08T10:22:01.689Z","trace":[{"column":17,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js","function":"ConnectionManager.connect","line":141,"method":"connect","native":false},{"column":5,"file":"node:internal/process/task_queues","function":"processTicksAndRejections","line":95,"method":null,"native":false},{"column":24,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":"ConnectionManager._connect","line":332,"method":"_connect","native":false},{"column":32,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":null,"line":250,"method":null,"native":false}]}
error: Could not connect to the database. Login failed for user 'sa'. {"name":"SequelizeAccessDeniedError","original":{"code":"ELOGIN"},"parent":{"code":"ELOGIN"},"stack":"SequelizeAccessDeniedError: Login failed for user 'sa'.\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js:144:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","timestamp":"2024-05-08T10:25:15.724Z"}
error: uncaughtException: Login failed for user 'sa'.
SequelizeAccessDeniedError: Login failed for user 'sa'.
    at ConnectionManager.connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\mssql\connection-manager.js:144:17)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ConnectionManager._connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:332:24)
    at D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:250:32 {"date":"Wed May 08 2024 15:55:15 GMT+0530 (India Standard Time)","error":{"name":"SequelizeAccessDeniedError","original":{"code":"ELOGIN"},"parent":{"code":"ELOGIN"}},"exception":true,"os":{"loadavg":[0,0,0],"uptime":1216942.093},"process":{"argv":["node","D:\\CPAI_Node\\demo_project\\src\\index.js"],"cwd":"D:\\CPAI_Node\\demo_project","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":19974,"external":3096784,"heapTotal":94736384,"heapUsed":46432304,"rss":132976640},"pid":17452,"uid":null,"version":"v20.10.0"},"stack":"SequelizeAccessDeniedError: Login failed for user 'sa'.\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js:144:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","timestamp":"2024-05-08T10:25:15.729Z","trace":[{"column":17,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js","function":"ConnectionManager.connect","line":144,"method":"connect","native":false},{"column":5,"file":"node:internal/process/task_queues","function":"processTicksAndRejections","line":95,"method":null,"native":false},{"column":24,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":"ConnectionManager._connect","line":332,"method":"_connect","native":false},{"column":32,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":null,"line":250,"method":null,"native":false}]}
error: Could not connect to the database. Failed to connect to 127.0.0.1:1433 - Could not connect (sequence) {"name":"SequelizeConnectionError","original":{"code":"ESOCKET"},"parent":{"code":"ESOCKET"},"stack":"SequelizeConnectionError: Failed to connect to 127.0.0.1:1433 - Could not connect (sequence)\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js:141:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","timestamp":"2024-05-08T10:25:54.361Z"}
error: uncaughtException: Failed to connect to 127.0.0.1:1433 - Could not connect (sequence)
SequelizeConnectionError: Failed to connect to 127.0.0.1:1433 - Could not connect (sequence)
    at ConnectionManager.connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\mssql\connection-manager.js:141:17)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ConnectionManager._connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:332:24)
    at D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:250:32 {"date":"Wed May 08 2024 15:55:54 GMT+0530 (India Standard Time)","error":{"name":"SequelizeConnectionError","original":{"code":"ESOCKET"},"parent":{"code":"ESOCKET"}},"exception":true,"os":{"loadavg":[0,0,0],"uptime":1216980.734},"process":{"argv":["node","D:\\CPAI_Node\\demo_project\\src\\index.js"],"cwd":"D:\\CPAI_Node\\demo_project","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":17067,"external":3093877,"heapTotal":95260672,"heapUsed":45489016,"rss":130965504},"pid":41656,"uid":null,"version":"v20.10.0"},"stack":"SequelizeConnectionError: Failed to connect to 127.0.0.1:1433 - Could not connect (sequence)\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js:141:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","timestamp":"2024-05-08T10:25:54.367Z","trace":[{"column":17,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js","function":"ConnectionManager.connect","line":141,"method":"connect","native":false},{"column":5,"file":"node:internal/process/task_queues","function":"processTicksAndRejections","line":95,"method":null,"native":false},{"column":24,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":"ConnectionManager._connect","line":332,"method":"_connect","native":false},{"column":32,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":null,"line":250,"method":null,"native":false}]}
error: Could not connect to the database. Failed to connect to 127.0.0.1:1433 - Could not connect (sequence) {"name":"SequelizeConnectionError","original":{"code":"ESOCKET"},"parent":{"code":"ESOCKET"},"stack":"SequelizeConnectionError: Failed to connect to 127.0.0.1:1433 - Could not connect (sequence)\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js:141:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","timestamp":"2024-05-08T10:46:02.960Z"}
error: uncaughtException: Failed to connect to 127.0.0.1:1433 - Could not connect (sequence)
SequelizeConnectionError: Failed to connect to 127.0.0.1:1433 - Could not connect (sequence)
    at ConnectionManager.connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\mssql\connection-manager.js:141:17)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ConnectionManager._connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:332:24)
    at D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:250:32 {"date":"Wed May 08 2024 16:16:02 GMT+0530 (India Standard Time)","error":{"name":"SequelizeConnectionError","original":{"code":"ESOCKET"},"parent":{"code":"ESOCKET"}},"exception":true,"os":{"loadavg":[0,0,0],"uptime":1218189.328},"process":{"argv":["node","D:\\CPAI_Node\\demo_project\\src\\index.js"],"cwd":"D:\\CPAI_Node\\demo_project","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":17067,"external":3093877,"heapTotal":94474240,"heapUsed":45496336,"rss":129970176},"pid":23080,"uid":null,"version":"v20.10.0"},"stack":"SequelizeConnectionError: Failed to connect to 127.0.0.1:1433 - Could not connect (sequence)\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js:141:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","timestamp":"2024-05-08T10:46:02.966Z","trace":[{"column":17,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js","function":"ConnectionManager.connect","line":141,"method":"connect","native":false},{"column":5,"file":"node:internal/process/task_queues","function":"processTicksAndRejections","line":95,"method":null,"native":false},{"column":24,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":"ConnectionManager._connect","line":332,"method":"_connect","native":false},{"column":32,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":null,"line":250,"method":null,"native":false}]}
error: Could not connect to the database. Connection lost - Unable to process incoming packet {"name":"SequelizeConnectionError","original":{"code":"ESOCKET"},"parent":{"code":"ESOCKET"},"stack":"SequelizeConnectionError: Connection lost - Unable to process incoming packet\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js:141:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","timestamp":"2024-05-08T10:51:33.285Z"}
error: uncaughtException: Connection lost - Unable to process incoming packet
SequelizeConnectionError: Connection lost - Unable to process incoming packet
    at ConnectionManager.connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\mssql\connection-manager.js:141:17)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ConnectionManager._connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:332:24)
    at D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:250:32 {"date":"Wed May 08 2024 16:21:33 GMT+0530 (India Standard Time)","error":{"name":"SequelizeConnectionError","original":{"code":"ESOCKET"},"parent":{"code":"ESOCKET"}},"exception":true,"os":{"loadavg":[0,0,0],"uptime":1218519.656},"process":{"argv":["node","D:\\CPAI_Node\\demo_project\\src\\index.js"],"cwd":"D:\\CPAI_Node\\demo_project","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":23337,"external":3100147,"heapTotal":94998528,"heapUsed":46353864,"rss":130818048},"pid":40732,"uid":null,"version":"v20.10.0"},"stack":"SequelizeConnectionError: Connection lost - Unable to process incoming packet\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js:141:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","timestamp":"2024-05-08T10:51:33.288Z","trace":[{"column":17,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js","function":"ConnectionManager.connect","line":141,"method":"connect","native":false},{"column":5,"file":"node:internal/process/task_queues","function":"processTicksAndRejections","line":95,"method":null,"native":false},{"column":24,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":"ConnectionManager._connect","line":332,"method":"_connect","native":false},{"column":32,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":null,"line":250,"method":null,"native":false}]}
error: Could not connect to the database. Unknown database 'express' {"name":"SequelizeConnectionError","original":{"code":"ER_BAD_DB_ERROR","errno":1049,"sqlMessage":"Unknown database 'express'","sqlState":"42000"},"parent":{"code":"ER_BAD_DB_ERROR","errno":1049,"sqlMessage":"Unknown database 'express'","sqlState":"42000"},"stack":"SequelizeConnectionError: Unknown database 'express'\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mysql\\connection-manager.js:126:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","timestamp":"2024-05-08T10:51:46.582Z"}
error: uncaughtException: Unknown database 'express'
SequelizeConnectionError: Unknown database 'express'
    at ConnectionManager.connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\mysql\connection-manager.js:126:17)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ConnectionManager._connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:332:24)
    at D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:250:32 {"date":"Wed May 08 2024 16:21:46 GMT+0530 (India Standard Time)","error":{"name":"SequelizeConnectionError","original":{"code":"ER_BAD_DB_ERROR","errno":1049,"sqlMessage":"Unknown database 'express'","sqlState":"42000"},"parent":{"code":"ER_BAD_DB_ERROR","errno":1049,"sqlMessage":"Unknown database 'express'","sqlState":"42000"}},"exception":true,"os":{"loadavg":[0,0,0],"uptime":1218532.953},"process":{"argv":["node","D:\\CPAI_Node\\demo_project\\src\\index.js"],"cwd":"D:\\CPAI_Node\\demo_project","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":18038,"external":3064485,"heapTotal":83648512,"heapUsed":62475424,"rss":122679296},"pid":38124,"uid":null,"version":"v20.10.0"},"stack":"SequelizeConnectionError: Unknown database 'express'\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mysql\\connection-manager.js:126:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","timestamp":"2024-05-08T10:51:46.585Z","trace":[{"column":17,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mysql\\connection-manager.js","function":"ConnectionManager.connect","line":126,"method":"connect","native":false},{"column":5,"file":"node:internal/process/task_queues","function":"processTicksAndRejections","line":95,"method":null,"native":false},{"column":24,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":"ConnectionManager._connect","line":332,"method":"_connect","native":false},{"column":32,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":null,"line":250,"method":null,"native":false}]}
error: Could not connect to the database. Failed to connect to 127.0.0.1:1433 - Could not connect (sequence) {"name":"SequelizeConnectionError","original":{"code":"ESOCKET"},"parent":{"code":"ESOCKET"},"stack":"SequelizeConnectionError: Failed to connect to 127.0.0.1:1433 - Could not connect (sequence)\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js:141:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","timestamp":"2024-05-08T11:03:01.053Z"}
error: uncaughtException: Failed to connect to 127.0.0.1:1433 - Could not connect (sequence)
SequelizeConnectionError: Failed to connect to 127.0.0.1:1433 - Could not connect (sequence)
    at ConnectionManager.connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\mssql\connection-manager.js:141:17)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ConnectionManager._connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:332:24)
    at D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:250:32 {"date":"Wed May 08 2024 16:33:01 GMT+0530 (India Standard Time)","error":{"name":"SequelizeConnectionError","original":{"code":"ESOCKET"},"parent":{"code":"ESOCKET"}},"exception":true,"os":{"loadavg":[0,0,0],"uptime":1219207.421},"process":{"argv":["node","D:\\CPAI_Node\\demo_project\\src\\index.js"],"cwd":"D:\\CPAI_Node\\demo_project","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":17067,"external":3093877,"heapTotal":94736384,"heapUsed":45501416,"rss":130002944},"pid":35928,"uid":null,"version":"v20.10.0"},"stack":"SequelizeConnectionError: Failed to connect to 127.0.0.1:1433 - Could not connect (sequence)\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js:141:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","timestamp":"2024-05-08T11:03:01.057Z","trace":[{"column":17,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js","function":"ConnectionManager.connect","line":141,"method":"connect","native":false},{"column":5,"file":"node:internal/process/task_queues","function":"processTicksAndRejections","line":95,"method":null,"native":false},{"column":24,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":"ConnectionManager._connect","line":332,"method":"_connect","native":false},{"column":32,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":null,"line":250,"method":null,"native":false}]}
error: Could not connect to the database. Failed to connect to 127.0.0.1:1433 - Could not connect (sequence) {"name":"SequelizeConnectionError","original":{"code":"ESOCKET"},"parent":{"code":"ESOCKET"},"stack":"SequelizeConnectionError: Failed to connect to 127.0.0.1:1433 - Could not connect (sequence)\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js:141:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","timestamp":"2024-05-08T11:09:07.155Z"}
error: uncaughtException: Failed to connect to 127.0.0.1:1433 - Could not connect (sequence)
SequelizeConnectionError: Failed to connect to 127.0.0.1:1433 - Could not connect (sequence)
    at ConnectionManager.connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\mssql\connection-manager.js:141:17)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ConnectionManager._connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:332:24)
    at D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:250:32 {"date":"Wed May 08 2024 16:39:07 GMT+0530 (India Standard Time)","error":{"name":"SequelizeConnectionError","original":{"code":"ESOCKET"},"parent":{"code":"ESOCKET"}},"exception":true,"os":{"loadavg":[0,0,0],"uptime":1219573.531},"process":{"argv":["node","D:\\CPAI_Node\\demo_project\\src\\index.js"],"cwd":"D:\\CPAI_Node\\demo_project","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":17067,"external":3093877,"heapTotal":95784960,"heapUsed":45482544,"rss":130580480},"pid":28556,"uid":null,"version":"v20.10.0"},"stack":"SequelizeConnectionError: Failed to connect to 127.0.0.1:1433 - Could not connect (sequence)\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js:141:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","timestamp":"2024-05-08T11:09:07.161Z","trace":[{"column":17,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js","function":"ConnectionManager.connect","line":141,"method":"connect","native":false},{"column":5,"file":"node:internal/process/task_queues","function":"processTicksAndRejections","line":95,"method":null,"native":false},{"column":24,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":"ConnectionManager._connect","line":332,"method":"_connect","native":false},{"column":32,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":null,"line":250,"method":null,"native":false}]}
error: Could not connect to the database. Login failed for user 'sa'. {"name":"SequelizeAccessDeniedError","original":{"code":"ELOGIN"},"parent":{"code":"ELOGIN"},"stack":"SequelizeAccessDeniedError: Login failed for user 'sa'.\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js:144:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","timestamp":"2024-05-08T11:17:36.430Z"}
error: uncaughtException: Login failed for user 'sa'.
SequelizeAccessDeniedError: Login failed for user 'sa'.
    at ConnectionManager.connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\mssql\connection-manager.js:144:17)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ConnectionManager._connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:332:24)
    at D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:250:32 {"date":"Wed May 08 2024 16:47:36 GMT+0530 (India Standard Time)","error":{"name":"SequelizeAccessDeniedError","original":{"code":"ELOGIN"},"parent":{"code":"ELOGIN"}},"exception":true,"os":{"loadavg":[0,0,0],"uptime":209.328},"process":{"argv":["node","D:\\CPAI_Node\\demo_project\\src\\index.js"],"cwd":"D:\\CPAI_Node\\demo_project","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":19972,"external":3096782,"heapTotal":95260672,"heapUsed":46350480,"rss":133021696},"pid":14492,"uid":null,"version":"v20.10.0"},"stack":"SequelizeAccessDeniedError: Login failed for user 'sa'.\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js:144:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","timestamp":"2024-05-08T11:17:36.435Z","trace":[{"column":17,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js","function":"ConnectionManager.connect","line":144,"method":"connect","native":false},{"column":5,"file":"node:internal/process/task_queues","function":"processTicksAndRejections","line":95,"method":null,"native":false},{"column":24,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":"ConnectionManager._connect","line":332,"method":"_connect","native":false},{"column":32,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":null,"line":250,"method":null,"native":false}]}
error: Could not connect to the database. Login failed for user 'sa'. {"name":"SequelizeAccessDeniedError","original":{"code":"ELOGIN"},"parent":{"code":"ELOGIN"},"stack":"SequelizeAccessDeniedError: Login failed for user 'sa'.\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js:144:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","timestamp":"2024-05-08T11:18:07.862Z"}
error: uncaughtException: Login failed for user 'sa'.
SequelizeAccessDeniedError: Login failed for user 'sa'.
    at ConnectionManager.connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\mssql\connection-manager.js:144:17)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ConnectionManager._connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:332:24)
    at D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:250:32 {"date":"Wed May 08 2024 16:48:07 GMT+0530 (India Standard Time)","error":{"name":"SequelizeAccessDeniedError","original":{"code":"ELOGIN"},"parent":{"code":"ELOGIN"}},"exception":true,"os":{"loadavg":[0,0,0],"uptime":240.75},"process":{"argv":["node","D:\\CPAI_Node\\demo_project\\src\\index.js"],"cwd":"D:\\CPAI_Node\\demo_project","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":19972,"external":3096782,"heapTotal":94892032,"heapUsed":46422744,"rss":133603328},"pid":9824,"uid":null,"version":"v20.10.0"},"stack":"SequelizeAccessDeniedError: Login failed for user 'sa'.\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js:144:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","timestamp":"2024-05-08T11:18:07.865Z","trace":[{"column":17,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js","function":"ConnectionManager.connect","line":144,"method":"connect","native":false},{"column":5,"file":"node:internal/process/task_queues","function":"processTicksAndRejections","line":95,"method":null,"native":false},{"column":24,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":"ConnectionManager._connect","line":332,"method":"_connect","native":false},{"column":32,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":null,"line":250,"method":null,"native":false}]}
error: Could not connect to the database. Failed to connect to 169.254.150.115:1433 in 15000ms {"name":"SequelizeConnectionError","original":{"code":"ETIMEOUT"},"parent":{"code":"ETIMEOUT"},"stack":"SequelizeConnectionError: Failed to connect to 169.254.150.115:1433 in 15000ms\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js:148:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","timestamp":"2024-05-08T11:19:29.380Z"}
error: uncaughtException: Failed to connect to 169.254.150.115:1433 in 15000ms
SequelizeConnectionError: Failed to connect to 169.254.150.115:1433 in 15000ms
    at ConnectionManager.connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\mssql\connection-manager.js:148:17)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ConnectionManager._connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:332:24)
    at D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:250:32 {"date":"Wed May 08 2024 16:49:29 GMT+0530 (India Standard Time)","error":{"name":"SequelizeConnectionError","original":{"code":"ETIMEOUT"},"parent":{"code":"ETIMEOUT"}},"exception":true,"os":{"loadavg":[0,0,0],"uptime":322.281},"process":{"argv":["node","D:\\CPAI_Node\\demo_project\\src\\index.js"],"cwd":"D:\\CPAI_Node\\demo_project","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":17067,"external":3093877,"heapTotal":94736384,"heapUsed":45924248,"rss":130469888},"pid":15924,"uid":null,"version":"v20.10.0"},"stack":"SequelizeConnectionError: Failed to connect to 169.254.150.115:1433 in 15000ms\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js:148:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","timestamp":"2024-05-08T11:19:29.385Z","trace":[{"column":17,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js","function":"ConnectionManager.connect","line":148,"method":"connect","native":false},{"column":5,"file":"node:internal/process/task_queues","function":"processTicksAndRejections","line":95,"method":null,"native":false},{"column":24,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":"ConnectionManager._connect","line":332,"method":"_connect","native":false},{"column":32,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":null,"line":250,"method":null,"native":false}]}
error: Could not connect to the database. Failed to connect to 169.254.150.115:1433 in 15000ms {"name":"SequelizeConnectionError","original":{"code":"ETIMEOUT"},"parent":{"code":"ETIMEOUT"},"stack":"SequelizeConnectionError: Failed to connect to 169.254.150.115:1433 in 15000ms\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js:148:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","timestamp":"2024-05-08T11:20:45.180Z"}
error: uncaughtException: Failed to connect to 169.254.150.115:1433 in 15000ms
SequelizeConnectionError: Failed to connect to 169.254.150.115:1433 in 15000ms
    at ConnectionManager.connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\mssql\connection-manager.js:148:17)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ConnectionManager._connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:332:24)
    at D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:250:32 {"date":"Wed May 08 2024 16:50:45 GMT+0530 (India Standard Time)","error":{"name":"SequelizeConnectionError","original":{"code":"ETIMEOUT"},"parent":{"code":"ETIMEOUT"}},"exception":true,"os":{"loadavg":[0,0,0],"uptime":398.078},"process":{"argv":["node","D:\\CPAI_Node\\demo_project\\src\\index.js"],"cwd":"D:\\CPAI_Node\\demo_project","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":17067,"external":3093877,"heapTotal":47812608,"heapUsed":45773360,"rss":87207936},"pid":13628,"uid":null,"version":"v20.10.0"},"stack":"SequelizeConnectionError: Failed to connect to 169.254.150.115:1433 in 15000ms\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js:148:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","timestamp":"2024-05-08T11:20:45.183Z","trace":[{"column":17,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js","function":"ConnectionManager.connect","line":148,"method":"connect","native":false},{"column":5,"file":"node:internal/process/task_queues","function":"processTicksAndRejections","line":95,"method":null,"native":false},{"column":24,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":"ConnectionManager._connect","line":332,"method":"_connect","native":false},{"column":32,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":null,"line":250,"method":null,"native":false}]}
error: Could not connect to the database. Login failed for user 'sa'. {"name":"SequelizeAccessDeniedError","original":{"code":"ELOGIN"},"parent":{"code":"ELOGIN"},"stack":"SequelizeAccessDeniedError: Login failed for user 'sa'.\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js:144:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","timestamp":"2024-05-08T11:22:25.472Z"}
error: uncaughtException: Login failed for user 'sa'.
SequelizeAccessDeniedError: Login failed for user 'sa'.
    at ConnectionManager.connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\mssql\connection-manager.js:144:17)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ConnectionManager._connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:332:24)
    at D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:250:32 {"date":"Wed May 08 2024 16:52:25 GMT+0530 (India Standard Time)","error":{"name":"SequelizeAccessDeniedError","original":{"code":"ELOGIN"},"parent":{"code":"ELOGIN"}},"exception":true,"os":{"loadavg":[0,0,0],"uptime":498.375},"process":{"argv":["node","D:\\CPAI_Node\\demo_project\\src\\index.js"],"cwd":"D:\\CPAI_Node\\demo_project","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":19972,"external":3096782,"heapTotal":94367744,"heapUsed":46389248,"rss":132689920},"pid":10016,"uid":null,"version":"v20.10.0"},"stack":"SequelizeAccessDeniedError: Login failed for user 'sa'.\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js:144:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","timestamp":"2024-05-08T11:22:25.476Z","trace":[{"column":17,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js","function":"ConnectionManager.connect","line":144,"method":"connect","native":false},{"column":5,"file":"node:internal/process/task_queues","function":"processTicksAndRejections","line":95,"method":null,"native":false},{"column":24,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":"ConnectionManager._connect","line":332,"method":"_connect","native":false},{"column":32,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":null,"line":250,"method":null,"native":false}]}
error: Could not connect to the database. Login failed for user 'sa'. {"name":"SequelizeAccessDeniedError","original":{"code":"ELOGIN"},"parent":{"code":"ELOGIN"},"stack":"SequelizeAccessDeniedError: Login failed for user 'sa'.\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js:144:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","timestamp":"2024-05-08T11:24:23.023Z"}
error: uncaughtException: Login failed for user 'sa'.
SequelizeAccessDeniedError: Login failed for user 'sa'.
    at ConnectionManager.connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\mssql\connection-manager.js:144:17)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ConnectionManager._connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:332:24)
    at D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:250:32 {"date":"Wed May 08 2024 16:54:23 GMT+0530 (India Standard Time)","error":{"name":"SequelizeAccessDeniedError","original":{"code":"ELOGIN"},"parent":{"code":"ELOGIN"}},"exception":true,"os":{"loadavg":[0,0,0],"uptime":615.921},"process":{"argv":["node","D:\\CPAI_Node\\demo_project\\src\\index.js"],"cwd":"D:\\CPAI_Node\\demo_project","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":19968,"external":3096778,"heapTotal":94892032,"heapUsed":46459808,"rss":133382144},"pid":4720,"uid":null,"version":"v20.10.0"},"stack":"SequelizeAccessDeniedError: Login failed for user 'sa'.\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js:144:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","timestamp":"2024-05-08T11:24:23.026Z","trace":[{"column":17,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js","function":"ConnectionManager.connect","line":144,"method":"connect","native":false},{"column":5,"file":"node:internal/process/task_queues","function":"processTicksAndRejections","line":95,"method":null,"native":false},{"column":24,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":"ConnectionManager._connect","line":332,"method":"_connect","native":false},{"column":32,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":null,"line":250,"method":null,"native":false}]}
error: Could not connect to the database. Login failed for user 'sa'. {"name":"SequelizeAccessDeniedError","original":{"code":"ELOGIN"},"parent":{"code":"ELOGIN"},"stack":"SequelizeAccessDeniedError: Login failed for user 'sa'.\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js:144:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","timestamp":"2024-05-09T05:50:55.305Z"}
error: uncaughtException: Login failed for user 'sa'.
SequelizeAccessDeniedError: Login failed for user 'sa'.
    at ConnectionManager.connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\mssql\connection-manager.js:144:17)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ConnectionManager._connect (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:332:24)
    at D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\connection-manager.js:250:32 {"date":"Thu May 09 2024 11:20:55 GMT+0530 (India Standard Time)","error":{"name":"SequelizeAccessDeniedError","original":{"code":"ELOGIN"},"parent":{"code":"ELOGIN"}},"exception":true,"os":{"loadavg":[0,0,0],"uptime":1498.203},"process":{"argv":["node","D:\\CPAI_Node\\demo_project\\src\\index.js"],"cwd":"D:\\CPAI_Node\\demo_project","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":20298,"external":3097108,"heapTotal":99872768,"heapUsed":49688016,"rss":135983104},"pid":15512,"uid":null,"version":"v20.10.0"},"stack":"SequelizeAccessDeniedError: Login failed for user 'sa'.\n    at ConnectionManager.connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js:144:17)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ConnectionManager._connect (D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32","timestamp":"2024-05-09T05:50:55.310Z","trace":[{"column":17,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\mssql\\connection-manager.js","function":"ConnectionManager.connect","line":144,"method":"connect","native":false},{"column":5,"file":"node:internal/process/task_queues","function":"processTicksAndRejections","line":95,"method":null,"native":false},{"column":24,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":"ConnectionManager._connect","line":332,"method":"_connect","native":false},{"column":32,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js","function":null,"line":250,"method":null,"native":false}]}
error: 
    status - 500 
    message - ValidationError: "firstName" length must be at least 3 characters long 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2024-05-09T06:20:15.820Z"}
error: 
    status - 500 
    message - ValidationError: "email" must be a valid email 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2024-05-09T06:22:15.999Z"}
error: 
      status - 400
      message - Authorization token is required 
      url - /api/v1/users/1 
      method - GET 
      IP - ::1
     {"timestamp":"2024-05-09T06:26:50.694Z"}
error: 
    status - 500 
    message - Error: Missing where attribute in the options parameter passed to findCreateFind.
    at Function.findCreateFind (D:\CPAI_Node\demo_project\node_modules\sequelize\src\model.js:2481:13)
    at _callee2$ (D:\CPAI_Node\demo_project\src\services\/user.service.js:12:27)
    at tryCatch (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at Object.apply (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:19:12)
    at Object.newUser (D:\CPAI_Node\demo_project\src\services\/user.service.js:11:21)
    at _callee3$ (D:\CPAI_Node\demo_project\src\controllers\/user.controller.js:51:36)
    at tryCatch (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at apply (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:19:12)
    at newUser (D:\CPAI_Node\demo_project\src\controllers\/user.controller.js:48:21)
    at Layer.handle [as handle_request] (D:\CPAI_Node\demo_project\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\CPAI_Node\demo_project\node_modules\express\lib\router\route.js:149:13)
    at newUserValidator (D:\CPAI_Node\demo_project\src\validators\/user.validator.js:14:5)
    at Layer.handle [as handle_request] (D:\CPAI_Node\demo_project\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\CPAI_Node\demo_project\node_modules\express\lib\router\route.js:149:13)
    at Route.dispatch (D:\CPAI_Node\demo_project\node_modules\express\lib\router\route.js:119:3)
    at Layer.handle [as handle_request] (D:\CPAI_Node\demo_project\node_modules\express\lib\router\layer.js:95:5)
    at D:\CPAI_Node\demo_project\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (D:\CPAI_Node\demo_project\node_modules\express\lib\router\index.js:346:12)
    at next (D:\CPAI_Node\demo_project\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\CPAI_Node\demo_project\node_modules\express\lib\router\index.js:175:3)
    at router (D:\CPAI_Node\demo_project\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (D:\CPAI_Node\demo_project\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\CPAI_Node\demo_project\node_modules\express\lib\router\index.js:328:13)
    at D:\CPAI_Node\demo_project\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\CPAI_Node\demo_project\node_modules\express\lib\router\index.js:346:12)
    at next (D:\CPAI_Node\demo_project\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\CPAI_Node\demo_project\node_modules\express\lib\router\index.js:175:3)
    at router (D:\CPAI_Node\demo_project\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (D:\CPAI_Node\demo_project\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\CPAI_Node\demo_project\node_modules\express\lib\router\index.js:328:13)
    at D:\CPAI_Node\demo_project\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\CPAI_Node\demo_project\node_modules\express\lib\router\index.js:346:12)
    at next (D:\CPAI_Node\demo_project\node_modules\express\lib\router\index.js:280:10)
    at logger (D:\CPAI_Node\demo_project\node_modules\morgan\index.js:144:5)
    at Layer.handle [as handle_request] (D:\CPAI_Node\demo_project\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\CPAI_Node\demo_project\node_modules\express\lib\router\index.js:328:13)
    at D:\CPAI_Node\demo_project\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\CPAI_Node\demo_project\node_modules\express\lib\router\index.js:346:12) 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2024-05-09T06:41:47.358Z"}
error: 
    status - 500 
    message - Error: Missing where attribute in the options parameter passed to findCreateFind.
    at Function.findCreateFind (D:\CPAI_Node\demo_project\node_modules\sequelize\src\model.js:2481:13)
    at _callee2$ (D:\CPAI_Node\demo_project\src\services\/user.service.js:12:27)
    at tryCatch (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at Object.apply (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:19:12)
    at Object.newUser (D:\CPAI_Node\demo_project\src\services\/user.service.js:11:21)
    at _callee3$ (D:\CPAI_Node\demo_project\src\controllers\/user.controller.js:50:36)
    at tryCatch (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at apply (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:19:12)
    at newUser (D:\CPAI_Node\demo_project\src\controllers\/user.controller.js:48:21)
    at Layer.handle [as handle_request] (D:\CPAI_Node\demo_project\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\CPAI_Node\demo_project\node_modules\express\lib\router\route.js:149:13)
    at newUserValidator (D:\CPAI_Node\demo_project\src\validators\/user.validator.js:14:5)
    at Layer.handle [as handle_request] (D:\CPAI_Node\demo_project\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\CPAI_Node\demo_project\node_modules\express\lib\router\route.js:149:13)
    at Route.dispatch (D:\CPAI_Node\demo_project\node_modules\express\lib\router\route.js:119:3)
    at Layer.handle [as handle_request] (D:\CPAI_Node\demo_project\node_modules\express\lib\router\layer.js:95:5)
    at D:\CPAI_Node\demo_project\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (D:\CPAI_Node\demo_project\node_modules\express\lib\router\index.js:346:12)
    at next (D:\CPAI_Node\demo_project\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\CPAI_Node\demo_project\node_modules\express\lib\router\index.js:175:3)
    at router (D:\CPAI_Node\demo_project\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (D:\CPAI_Node\demo_project\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\CPAI_Node\demo_project\node_modules\express\lib\router\index.js:328:13)
    at D:\CPAI_Node\demo_project\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\CPAI_Node\demo_project\node_modules\express\lib\router\index.js:346:12)
    at next (D:\CPAI_Node\demo_project\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\CPAI_Node\demo_project\node_modules\express\lib\router\index.js:175:3)
    at router (D:\CPAI_Node\demo_project\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (D:\CPAI_Node\demo_project\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\CPAI_Node\demo_project\node_modules\express\lib\router\index.js:328:13)
    at D:\CPAI_Node\demo_project\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\CPAI_Node\demo_project\node_modules\express\lib\router\index.js:346:12)
    at next (D:\CPAI_Node\demo_project\node_modules\express\lib\router\index.js:280:10)
    at logger (D:\CPAI_Node\demo_project\node_modules\morgan\index.js:144:5)
    at Layer.handle [as handle_request] (D:\CPAI_Node\demo_project\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\CPAI_Node\demo_project\node_modules\express\lib\router\index.js:328:13)
    at D:\CPAI_Node\demo_project\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\CPAI_Node\demo_project\node_modules\express\lib\router\index.js:346:12) 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2024-05-09T06:42:39.273Z"}
error: 
    status - 500 
    message - Error: Username already exists
    at forEach (D:\CPAI_Node\demo_project\src\services\/user.service.js:16:13)
    at Array.forEach (<anonymous>)
    at _callee2$ (D:\CPAI_Node\demo_project\src\services\/user.service.js:14:13)
    at tryCatch (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2024-05-09T06:51:57.551Z"}
error: 
    status - 500 
    message - Error: User already exists
    at forEach (D:\CPAI_Node\demo_project\src\services\/user.service.js:16:13)
    at Array.forEach (<anonymous>)
    at _callee2$ (D:\CPAI_Node\demo_project\src\services\/user.service.js:14:13)
    at tryCatch (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2024-05-09T06:53:32.198Z"}
error: 
    status - 500 
    message - TypeError: "flag" is read-only
    at _readOnlyError (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\readOnlyError.js:2:9)
    at forEach (D:\CPAI_Node\demo_project\src\services\/user.service.js:19:15)
    at Array.forEach (<anonymous>)
    at _callee2$ (D:\CPAI_Node\demo_project\src\services\/user.service.js:16:13)
    at tryCatch (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2024-05-09T06:58:20.996Z"}
error: 
    status - 500 
    message - ReferenceError: data is not defined
    at _callee2$ (D:\CPAI_Node\demo_project\src\services\/user.service.js:29:10)
    at tryCatch (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2024-05-09T06:59:00.289Z"}
error: 
    status - 500 
    message - ReferenceError: data is not defined
    at _callee2$ (D:\CPAI_Node\demo_project\src\services\/user.service.js:29:10)
    at tryCatch (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2024-05-09T06:59:19.226Z"}
error: 
    status - 500 
    message - ReferenceError: data is not defined
    at _callee2$ (D:\CPAI_Node\demo_project\src\services\/user.service.js:29:10)
    at tryCatch (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2024-05-09T07:00:15.111Z"}
error: 
    status - 500 
    message - Error: Username already exists
    at forEach (D:\CPAI_Node\demo_project\src\services\/user.service.js:17:13)
    at Array.forEach (<anonymous>)
    at _callee2$ (D:\CPAI_Node\demo_project\src\services\/user.service.js:15:13)
    at tryCatch (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2024-05-09T07:03:37.051Z"}
error: 
    status - 500 
    message - Error: Username already exists
    at forEach (D:\CPAI_Node\demo_project\src\services\/user.service.js:17:13)
    at Array.forEach (<anonymous>)
    at _callee2$ (D:\CPAI_Node\demo_project\src\services\/user.service.js:15:13)
    at tryCatch (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2024-05-09T07:03:38.320Z"}
error: 
    status - 500 
    message - Error: Username already exists
    at forEach (D:\CPAI_Node\demo_project\src\services\/user.service.js:17:13)
    at Array.forEach (<anonymous>)
    at _callee2$ (D:\CPAI_Node\demo_project\src\services\/user.service.js:15:13)
    at tryCatch (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2024-05-09T07:08:15.274Z"}
error: uncaughtException: data is not defined
ReferenceError: data is not defined
    at _callee3$ (D:\CPAI_Node\demo_project\src\controllers\/user.controller.js:60:15)
    at tryCatch (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.throw (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _throw (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {"date":"Thu May 09 2024 12:39:46 GMT+0530 (India Standard Time)","error":{},"exception":true,"os":{"loadavg":[0,0,0],"uptime":6229.078},"process":{"argv":["node","D:\\CPAI_Node\\demo_project\\src\\index.js"],"cwd":"D:\\CPAI_Node\\demo_project","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":121065,"external":3197875,"heapTotal":101146624,"heapUsed":59230184,"rss":139038720},"pid":18384,"uid":null,"version":"v20.10.0"},"stack":"ReferenceError: data is not defined\n    at _callee3$ (D:\\CPAI_Node\\demo_project\\src\\controllers\\/user.controller.js:60:15)\n    at tryCatch (D:\\CPAI_Node\\demo_project\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:45:16)\n    at Generator.<anonymous> (D:\\CPAI_Node\\demo_project\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:133:17)\n    at Generator.throw (D:\\CPAI_Node\\demo_project\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:74:21)\n    at asyncGeneratorStep (D:\\CPAI_Node\\demo_project\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n    at _throw (D:\\CPAI_Node\\demo_project\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:25:9)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-05-09T07:09:46.195Z","trace":[{"column":15,"file":"D:\\CPAI_Node\\demo_project\\src\\controllers\\/user.controller.js","function":"_callee3$","line":60,"method":null,"native":false},{"column":16,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js","function":"tryCatch","line":45,"method":null,"native":false},{"column":17,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js","function":null,"line":133,"method":null,"native":false},{"column":21,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js","function":"Generator.throw","line":74,"method":"throw","native":false},{"column":24,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js","function":"asyncGeneratorStep","line":3,"method":null,"native":false},{"column":9,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js","function":"_throw","line":25,"method":null,"native":false},{"column":5,"file":"node:internal/process/task_queues","function":"processTicksAndRejections","line":95,"method":null,"native":false}]}
error: uncaughtException: data is not defined
ReferenceError: data is not defined
    at _callee3$ (D:\CPAI_Node\demo_project\src\controllers\/user.controller.js:60:15)
    at tryCatch (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.throw (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _throw (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {"date":"Thu May 09 2024 12:40:26 GMT+0530 (India Standard Time)","error":{},"exception":true,"os":{"loadavg":[0,0,0],"uptime":6269.718},"process":{"argv":["node","D:\\CPAI_Node\\demo_project\\src\\index.js"],"cwd":"D:\\CPAI_Node\\demo_project","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":121065,"external":3197875,"heapTotal":101408768,"heapUsed":59225360,"rss":139075584},"pid":12412,"uid":null,"version":"v20.10.0"},"stack":"ReferenceError: data is not defined\n    at _callee3$ (D:\\CPAI_Node\\demo_project\\src\\controllers\\/user.controller.js:60:15)\n    at tryCatch (D:\\CPAI_Node\\demo_project\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:45:16)\n    at Generator.<anonymous> (D:\\CPAI_Node\\demo_project\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:133:17)\n    at Generator.throw (D:\\CPAI_Node\\demo_project\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:74:21)\n    at asyncGeneratorStep (D:\\CPAI_Node\\demo_project\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n    at _throw (D:\\CPAI_Node\\demo_project\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:25:9)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2024-05-09T07:10:26.823Z","trace":[{"column":15,"file":"D:\\CPAI_Node\\demo_project\\src\\controllers\\/user.controller.js","function":"_callee3$","line":60,"method":null,"native":false},{"column":16,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js","function":"tryCatch","line":45,"method":null,"native":false},{"column":17,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js","function":null,"line":133,"method":null,"native":false},{"column":21,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js","function":"Generator.throw","line":74,"method":"throw","native":false},{"column":24,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js","function":"asyncGeneratorStep","line":3,"method":null,"native":false},{"column":9,"file":"D:\\CPAI_Node\\demo_project\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js","function":"_throw","line":25,"method":null,"native":false},{"column":5,"file":"node:internal/process/task_queues","function":"processTicksAndRejections","line":95,"method":null,"native":false}]}
error: 
    status - 500 
    message - Error: Username already exists
    at forEach (D:\CPAI_Node\demo_project\src\services\/user.service.js:17:13)
    at Array.forEach (<anonymous>)
    at _callee2$ (D:\CPAI_Node\demo_project\src\services\/user.service.js:15:13)
    at tryCatch (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2024-05-09T07:11:05.784Z"}
error: 
    status - 500 
    message - Error: Username already exists
    at forEach (D:\CPAI_Node\demo_project\src\services\/user.service.js:17:13)
    at Array.forEach (<anonymous>)
    at _callee2$ (D:\CPAI_Node\demo_project\src\services\/user.service.js:15:13)
    at tryCatch (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2024-05-09T07:11:07.356Z"}
error: 
    status - 500 
    message - Error: Username already exists
    at forEach (D:\CPAI_Node\demo_project\src\services\/user.service.js:17:13)
    at Array.forEach (<anonymous>)
    at _callee2$ (D:\CPAI_Node\demo_project\src\services\/user.service.js:15:13)
    at tryCatch (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2024-05-09T07:11:10.792Z"}
error: 
    status - 500 
    message - Error: Username already exists
    at forEach (D:\CPAI_Node\demo_project\src\services\/user.service.js:17:13)
    at Array.forEach (<anonymous>)
    at _callee2$ (D:\CPAI_Node\demo_project\src\services\/user.service.js:15:13)
    at tryCatch (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2024-05-09T07:11:17.616Z"}
error: 
    status - 500 
    message - Error: Username already exists
    at forEach (D:\CPAI_Node\demo_project\src\services\/user.service.js:17:13)
    at Array.forEach (<anonymous>)
    at _callee2$ (D:\CPAI_Node\demo_project\src\services\/user.service.js:15:13)
    at tryCatch (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2024-05-09T07:11:38.967Z"}
error: 
    status - 500 
    message - Error: Username already exists
    at forEach (D:\CPAI_Node\demo_project\src\services\/user.service.js:17:13)
    at Array.forEach (<anonymous>)
    at _callee2$ (D:\CPAI_Node\demo_project\src\services\/user.service.js:15:13)
    at tryCatch (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2024-05-09T07:12:35.096Z"}
error: 
    status - 500 
    message - ReferenceError: data is not defined
    at _callee2$ (D:\CPAI_Node\demo_project\src\services\/user.service.js:23:10)
    at tryCatch (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2024-05-09T07:13:07.056Z"}
error: 
    status - 500 
    message - Error: Username already exists
    at forEach (D:\CPAI_Node\demo_project\src\services\/user.service.js:15:13)
    at Array.forEach (<anonymous>)
    at _callee2$ (D:\CPAI_Node\demo_project\src\services\/user.service.js:13:13)
    at tryCatch (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2024-05-09T07:13:51.963Z"}
error: 
    status - 500 
    message - Error: Username already exists
    at forEach (D:\CPAI_Node\demo_project\src\services\/user.service.js:15:13)
    at Array.forEach (<anonymous>)
    at _callee2$ (D:\CPAI_Node\demo_project\src\services\/user.service.js:13:13)
    at tryCatch (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2024-05-09T07:13:58.555Z"}
error: 
    status - 500 
    message - Error: Username already exists
    at _callee2$ (D:\CPAI_Node\demo_project\src\services\/user.service.js:20:11)
    at tryCatch (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2024-05-09T07:19:55.767Z"}
error: 
    status - 500 
    message - Error: Username already exists
    at _callee2$ (D:\CPAI_Node\demo_project\src\services\/user.service.js:20:11)
    at tryCatch (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2024-05-09T07:19:57.972Z"}
error: 
    status - 500 
    message - Error: Username already exists
    at _callee2$ (D:\CPAI_Node\demo_project\src\services\/user.service.js:20:11)
    at tryCatch (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2024-05-09T07:20:04.905Z"}
error: 
    status - 500 
    message - Error: Username already exists
    at _callee2$ (D:\CPAI_Node\demo_project\src\services\/user.service.js:20:11)
    at tryCatch (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2024-05-09T07:20:06.537Z"}
error: 
    status - 500 
    message - Error: User already exists
    at _callee2$ (D:\CPAI_Node\demo_project\src\services\/user.service.js:19:11)
    at tryCatch (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2024-05-09T07:25:08.137Z"}
error: 
    status - 500 
    message - Error: WHERE parameter "firstname" has invalid "undefined" value
    at MSSQLQueryGenerator.whereItemQuery (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\query-generator.js:2445:13)
    at D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\query-generator.js:2434:25
    at Array.forEach (<anonymous>)
    at MSSQLQueryGenerator.whereItemsQuery (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\query-generator.js:2432:35)
    at MSSQLQueryGenerator.getWhereConditions (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\query-generator.js:2860:19)
    at MSSQLQueryGenerator.selectQuery (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\query-generator.js:1460:28)
    at MSSqlQueryInterface.select (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\query-interface.js:1002:27)
    at Function.findAll (D:\CPAI_Node\demo_project\node_modules\sequelize\src\model.js:1824:47)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Function.findOne (D:\CPAI_Node\demo_project\node_modules\sequelize\src\model.js:1998:12) 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2024-05-09T07:28:57.695Z"}
error: 
    status - 500 
    message - Error: WHERE parameter "firstname" has invalid "undefined" value
    at MSSQLQueryGenerator.whereItemQuery (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\query-generator.js:2445:13)
    at D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\query-generator.js:2434:25
    at Array.forEach (<anonymous>)
    at MSSQLQueryGenerator.whereItemsQuery (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\query-generator.js:2432:35)
    at MSSQLQueryGenerator.getWhereConditions (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\query-generator.js:2860:19)
    at MSSQLQueryGenerator.selectQuery (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\query-generator.js:1460:28)
    at MSSqlQueryInterface.select (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\query-interface.js:1002:27)
    at Function.findAll (D:\CPAI_Node\demo_project\node_modules\sequelize\src\model.js:1824:47)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Function.findOne (D:\CPAI_Node\demo_project\node_modules\sequelize\src\model.js:1998:12) 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2024-05-09T07:29:05.474Z"}
error: 
    status - 500 
    message - Error: WHERE parameter "firstname" has invalid "undefined" value
    at MSSQLQueryGenerator.whereItemQuery (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\query-generator.js:2445:13)
    at D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\query-generator.js:2434:25
    at Array.forEach (<anonymous>)
    at MSSQLQueryGenerator.whereItemsQuery (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\query-generator.js:2432:35)
    at MSSQLQueryGenerator.getWhereConditions (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\query-generator.js:2860:19)
    at MSSQLQueryGenerator.selectQuery (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\query-generator.js:1460:28)
    at MSSqlQueryInterface.select (D:\CPAI_Node\demo_project\node_modules\sequelize\src\dialects\abstract\query-interface.js:1002:27)
    at Function.findAll (D:\CPAI_Node\demo_project\node_modules\sequelize\src\model.js:1824:47)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Function.findOne (D:\CPAI_Node\demo_project\node_modules\sequelize\src\model.js:1998:12) 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2024-05-09T07:30:17.154Z"}
error: 
    status - 500 
    message - Error: User already exists
    at _callee2$ (D:\CPAI_Node\demo_project\src\services\/user.service.js:22:11)
    at tryCatch (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2024-05-09T07:30:38.288Z"}
error: 
    status - 500 
    message - Error: User already exists
    at _callee2$ (D:\CPAI_Node\demo_project\src\services\/user.service.js:22:11)
    at tryCatch (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2024-05-09T07:30:41.755Z"}
error: 
    status - 500 
    message - Error: User already exists
    at _callee2$ (D:\CPAI_Node\demo_project\src\services\/user.service.js:22:11)
    at tryCatch (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2024-05-09T07:31:26.093Z"}
error: 
    status - 500 
    message - Error: User already exists
    at _callee2$ (D:\CPAI_Node\demo_project\src\services\/user.service.js:22:11)
    at tryCatch (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2024-05-09T07:31:27.574Z"}
error: 
    status - 500 
    message - Error: User already exists
    at _callee2$ (D:\CPAI_Node\demo_project\src\services\/user.service.js:22:11)
    at tryCatch (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2024-05-09T07:31:33.565Z"}
error: 
    status - 500 
    message - ReferenceError: data is not defined
    at _callee5$ (D:\CPAI_Node\demo_project\src\services\/user.service.js:51:10)
    at tryCatch (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/1 
    method - GET 
    IP - ::1
   {"timestamp":"2024-05-09T07:48:54.092Z"}
error: 
    status - 500 
    message - TypeError: _base.error is not a constructor
    at _callee5$ (D:\CPAI_Node\demo_project\src\services\/user.service.js:47:11)
    at tryCatch (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/50 
    method - GET 
    IP - ::1
   {"timestamp":"2024-05-09T07:49:19.884Z"}
error: 
    status - 500 
    message - Error: Please ensure that the id enter is valid ID
    at _callee5$ (D:\CPAI_Node\demo_project\src\services\/user.service.js:47:11)
    at tryCatch (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/50 
    method - GET 
    IP - ::1
   {"timestamp":"2024-05-09T07:50:27.213Z"}
error: 
    status - 500 
    message - Error: Please ensure that the id enter is valid ID
    at _callee5$ (D:\CPAI_Node\demo_project\src\services\/user.service.js:47:11)
    at tryCatch (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/50 
    method - GET 
    IP - ::1
   {"timestamp":"2024-05-09T07:52:36.518Z"}
error: 
    status - 500 
    message - Error: Invlid ID
    at _callee3$ (D:\CPAI_Node\demo_project\src\services\/user.service.js:33:11)
    at tryCatch (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:133:17)
    at Generator.next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (D:\CPAI_Node\demo_project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/50 
    method - PUT 
    IP - ::1
   {"timestamp":"2024-05-09T07:59:47.887Z"}
